### ISSUE TITLE
Translation up to date or not wording & icons - in Translations Info box

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-translations#1]
At start of issue, straw proposal wording:
* When translation is of the latest version of the English original:
> [icon] Translation up-to-date with English version. 
> Translation updated: 00 Mon 0000. English updated: 00 Mon 0000.
* When the English version has been updated since the translation was updated, so the translation is not of the latest English version:
> [icon] English version updated since this translation: [Change log](@@). 
> English updated: 00 Mon 0000. Translation updated: 00 Mon 0000.

See latest wording and icon proposal in [mock-up](https://w3c.github.io/wai-translation-playground/people-use-web/)

In your comment you might want to quote the wording that you are commenting on, since the wording in the mock-up might change throughout the life of this issue.

**Comment by notabene** [comment]
Is “English” going to be understood as “official”?
eg WCAG are pointing to “Version originale (anglais) :” in French.
Suggestion: “Official English version” or “Original English version” to remove any ambiguity as to which one is the original.

**Comment by r12a** [comment]
Minor nit-pick: the original version is not always english for i18n articles, so 'official', or 'authoritative', or similar, might be better.

**Comment by r12a** [comment]
Another small suggestion: list updates chronologically.

> Traduction mise à jour avec la version anglaise.
> Mise à jour de la traduction: 12 Sep 2018. Anglais mis à jour: 15 May 2017. 

Somehow i'd find it easier to compare the dates if they were in chronological order from the line start. (Not a big deal.)

**Comment by slhenry** [comment]
> Minor nit-pick: the original version is not always english for i18n articles...

Right, so then the original version language would get the "original" designation and not the English translation. :-)

> ... so 'official', or 'authoritative', or similar, might be better.

We thought carefully about what to call non-Authorized translations for the [WCAG Translations page](https://www.w3.org/WAI/standards-guidelines/wcag/translations/). We settled on:
* [Authorized Translations](http://www.w3.org/2005/02/TranslationPolicy) follow a formal review process and are endorsed by W3C.
* [Unofficial translations](http://www.w3.org/Consortium/Translation/#auth) are not reviewed and are not endorsed by W3C.

which also matches the heading at https://www.w3.org/Consortium/Translation/#auth

**Comment by slhenry** [comment]
Acknowledging:
> Somehow i'd find it easier to compare the dates if they were in chronological order from the line start. (Not a big deal.)

I **really appreciate** your perspective **and** your indication that it's "Not a big deal" to help us address it with other perspectives.

> Translation up-to-date with the English version. 
> Translation updated: 00 Mon 2000. English updated: 00 Mon 2000.

Rationale: First shows the translation date, which will always be more recent than the English original, and may change as the translation is tweaked.

> English version updated since this translation: [Diff|Change-log]. 
> English updated: 00 Mon 2000. Translation updated: 00 Mon 2000.

Rationale: First shows that the English original has been updated and the translation is not up-to-date.

/me notes this makes sense to her and is very aware that it may not to others

**Comment by r12a** [comment]
> Right, so then the original version language would get the "original" designation and not the English translation. :-)

Well, actually, i18n always treats the English version as the canonical one, regardless of which language came first, and so that's always the one we point to.  One reason for this is that more people, including the WG, are able to review an english version during development and ensure that it is authoritative, ie. there's a practical reason rather than just a rule that it should be english.

**Comment by slhenry** [comment]
"... [English original](@@)." at end of first sentence.

(also "English (Original)" first item in vertical list list under secondary navigation)
