### ISSUE TITLE
Related info: additional links

### ISSUE THREAD

**Issue by r12a** [w3c/wai-translations#10]
> Related info
>     Read this!: Guiding users to translated pages

Actually, you may want to link to https://www.w3.org/International/techniques/authoring-html.en?open=navigation, since that points to other relevant articles, and a number of recommended do's and don'ts.

**Comment by slhenry** [comment]
Well this wiki page is for people figuring out the user interface, process, etc., rather than people doing the translations. I think that is too much info for this purpose.

I added it to the [Instructions to Translators section](https://github.com/w3c/wai-translations/wiki/WAI-Translations-Overall-Approach,-Issues,-etc#instructions-to-translators)

**Comment by r12a** [comment]
Um. Am i missing something?  The link i suggested leads to a list of techniques about how to design HTML pages - it's not instructions to translators at all.  For example, if you click on "Linking to localized content" or "Using content negotiation" you'll find a list of do's and don'ts and lists of related articles that address the questions in the design issues you have on github.

**Comment by slhenry** [comment]
Interesting disconnect. Here's what I did from your first comment, that is, **here's an example user experience** for you :-)
* clicked on https://www.w3.org/International/techniques/authoring-html.en?open=navigation
* Read h1 "Internationalization techniques: Authoring HTML & CSS"
* Read the big words on blue background: Characters, Language, Markup & text, Text direction
* Selected "Expand all" and got lots & lots of info
* skimmed a bit (maybe followed a few links)
* decided that's way too much information that is not directly relevant to the issues we're exploring in [WAI Translations](https://www.w3.org/wiki/WAI_Translations)

Then after your re-opening comment, I looked more (and I think ended up doing a find-in-page for "linking to") and **finally** figured out that you were referring **only** to the "Navigation" blue item and the expanded info under that. It was below the fold when I opened the page and I never saw it -- even when scrolled down in skimming, it didn't catch my attention.

I'll leave that for you to consider if you want to do anything different for your user experience (e.g., link with "?open=navigation" should place the focus there).

<hr>

**I updated [Background](https://www.w3.org/wiki/WAI_Translations#Background) with more info. Feel free to edit that.** I'll also add links to specific articles throughout [WAI Translations](https://www.w3.org/wiki/WAI_Translations) where relevant -- and you're welcome to. (However, I don't think it's usable to link within https://www.w3.org/International/techniques/authoring-html given my user experience.)

**Comment by r12a** [comment]
@slhenry thanks for the user feedback!  The bug where the page wasn't bringing the relevant stuff above the fold should now be fixed.  Try it with

https://www.w3.org/International/techniques/authoring-html.en?open=navigation&open=contentneg&open=linkloc#linkloc

which, unlike the previous link, also opens up the two relevant subsections.
