### ISSUE TITLE
Using GitHub, Markdown, HTML: translators who can't code

### ISSUE THREAD

**Issue by r12a** [w3c/wai-translations#11]
> Some potentially good translators may not be comfortable with GitHub, Markdown, &/or HTML. We don't want that to be a limiting factor.

On the other hand, my experience is that translators who don't understand how to write HTML provide bad translations (eg. translating element names, not translating attribute values, etc.).  

> For those who don't want to mess with it – Will we offer that they can submit the translation in another format (e.g., word processing) and we put it in format on GitHub? Do we have sufficient resources to do it short-term and long-term? It is likely people from EOWG, IG, and other would step up to help with this.

I think that's rather ambitious.  At times for i18n translations i found it hard to keep up with simply checking translations and sending feedback about errors. Recreating a page from a Word document can be very time-consuming, and actually can sometimes be more difficult than it appears, in terms of getting the right things in the right place.  Also, don't forget that attribute values, such as alt text, (which are not necessarily visible when the page is viewed) also need to be translated.

For i18n translations we allow translators to use GitHub PRs if they feel comfortable with GH, but can also provide and receive files in a zip for those who aren't.

**Comment by notabene** [comment]
In your experience @r12a must we set the process in stone early or is this something that we can make up as we go?

**Comment by yatil** [comment]
I plan to allow direct forking a translation from the English version. We have to look into some of the tooling anyway. And we should be welcoming to translations and we need to give good guidance anyways.

**Comment by r12a** [comment]
> In your experience @r12a must we set the process in stone early or is this something that we can make up as we go?

Let me just say that i wouldn't go down that route, because it's time consuming enough to work with HTML.

**Comment by slhenry** [comment]
Current plan is to provide a file for translators that has translation instructions and text to translate highlighted [like this](https://docs.google.com/document/d/1oVOIXH5mVvJSmznyWVU4A4N7E6vCOeHvYbpdAJvpbU0/edit).

Given the **complexity of our markdown & markup**, and the number of errors from the first round of translations, I think this will be most efficient overall. That is, yes it takes some time to prepare that file, yet I think it will cut down on much of the QA back-and-forth.

**Comment by r12a** [comment]
I noticed a couple of places where [ ] characters are not shaded yellow, eg.

> If you translate the [VTT file]

Are those characters part of the text read by the user?  If so, they're likely to need translation in languages like Japanese.

**Comment by notabene** [comment]
> I noticed a couple of places where [ ] characters are not shaded yellow, eg.
> 
> > If you translate the [VTT file]

I think there's a URL missing, this is supposed to be a plain Markdown link.
Help @yatil ? ;)

**Comment by yatil** [comment]
The [ ] characters are part of the link.

**Comment by slhenry** [comment]
Instructions say:
> Some links are formatted with brackets and parentheses; for example:
> ```[text](filename.html)```
> Make sure to keep these together.

Once we settle on link format, I'll try to make that even more clear.
