### ISSUE TITLE
All Translations - French categorizing pages

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-translations#120]
Ref: https://www.w3.org/WAI/translations/#franais-french

Hey @remibetin I just skimmed this. Probably you already have on it on your list. Just in case not, I see the heading:
> Conseils pour démarrer
and assume we also want one for Making Audio and Video Media Accessible
?

**Comment by remibetin** [comment]
@shawna-slh Good catch! 
I've found the source of the problem and opened a PR: https://github.com/w3c/wai-website-theme/pull/65
