### ISSUE TITLE
German - Introduction to Web Accessibility 

### ISSUE THREAD

**Issue by alexejrotar** [w3c/wai-translations#127]
I would like to  translate into german  the following resource:
- Page URL: https://www.w3.org/WAI/fundamentals/accessibility-intro/
- Link to file in GitHub: https://github.com/w3c/wai-intro-accessibility/edit/gh-pages/content/index.md

I have read the information on Translating WAI Documents at https://www.w3.org/WAI/about/translating/

I will wait for confirmation that the resource is ready for translation.

**Comment by remibetin** [comment]
Hi @alexejrotar,

Thank you for volunteering to translate this resource into German!

I need to make small code updates to this resource before you can proceed with this translation. I hope to publish them in the next few days.

If you don't hear from me by Thursday, feel free to send a comment here.

**Comment by remibetin** [comment]
Hi @alexejrotar,
 
The small code updates haven been published: you can now proceed with this translation! 🚀 

The immediate next step is described here: https://www.w3.org/WAI/about/translating/step-by-step/#start-translation

You will also find more guidance on WAI website, and particularly in the following resources:
- [Creating a Translation](https://www.w3.org/WAI/about/translating/guides/new-translation/)
- [Translation Guidance](https://www.w3.org/WAI/about/translating/guides/translation-guidance/)
- [Using GitHub](https://www.w3.org/WAI/about/translating/guides/using-github/)

Please let me know (in this issue or via email) when you have questions or need any additional help.

**Comment by remibetin** [comment]
This translation is ready for review! 🎉  

Reviewers are welcome to add their comments and collaborate with the translator in the related Pull Request: https://github.com/w3c/wai-intro-accessibility/pull/88

**Comment by remibetin** [comment]
Reviewed by @j9t and me. See https://github.com/w3c/wai-intro-accessibility/pull/88#pullrequestreview-1878243807

**Comment by remibetin** [comment]
Ready to publish 🚀

**Comment by remibetin** [comment]
This translation has been published today 🚀  Thank you @alexejrotar @j9t!
