### ISSUE TITLE
English in list - at top, ABC order, or both?

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-translations#13]
In list of languages available, where should English be? 

See options pros & cons in the wiki section: [English in the list](https://www.w3.org/wiki/WAI_Translations#English_in_the_list).

**Comment by notabene** [comment]
"English original" as first item would do the trick for me, perhaps if we turn it around like: "Original: English", plus second link in alphabetical order as some people (screen reader users for instance) may look into list of links and look for "e—".

**Comment by yatil** [comment]
I think putting it in twice will look weird. We won’t have too many translations in the beginning, so having it as the first item and maybe bold and add original in some form should be enough for now. If we have German and French translations, the list would look like:

* Original: English
* Deutsch
* English
* Français

This looks really broken.

* Original: English
* Deutsch
* Français

would work for me, and then we can revisit once we hit a critical mass of translations.

**Comment by notabene** [comment]
+1 for your proposition @yatil (revisit later after critical mass) although in this case I'd prefer “English: Original” for screen reader / keyboard users.

**Comment by slhenry** [comment]
+1 for English at the beginning only

+1 for "English (Original)" or "English: Original” or similar

-1 for too much reliance on "then we can revisit once we hit a critical mass of translations" approach. Best to figure it out now as much as feasible and not have to make UI changes later that will annoy (or worse) existing users.

**Comment by yatil** [comment]
Ok. Then let’s annoy users now. ;-)

**Comment by slhenry** [comment]
Decided: "English (Original)" first item in vertical list list under secondary navigation. "English" first in horizontal list at top.
