### ISSUE TITLE
Bahasa Indonesia - Tips for Getting Started

### ISSUE THREAD

**Issue by frirasyidi** [w3c/wai-translations#130]
I would like to  translate into Bahasa Indonesia the following resource:
- Page URL: https://www.w3.org/WAI/tips/

I have read the information on Translating WAI Documents at https://www.w3.org/WAI/about/translating/

I will wait for confirmation that the resource is ready for translation.

**Comment by remibetin** [comment]
@frirasyidi I confirm that this resource is ready for you to translate: thank you for volunteering to translate this priority resource!

My suggested approach would be to start translating this resource after #132 & #133 updates.

**Comment by frirasyidi** [comment]
The translation is in progress.
PR: https://github.com/w3c/wai-quick-start/pull/393

**Comment by frirasyidi** [comment]
@remibetin this one is ready for review.

**Comment by remibetin** [comment]
This translation is ready for review! 🎉

Reviewers are welcome to add their comments and collaborate with the translator in the related Pull Request: https://github.com/w3c/wai-quick-start/pull/393

**Comment by remibetin** [comment]
Hi @frirasyidi 

I have finished reviewing your translation: I have added comments in the Pull Request for your consideration: see https://github.com/w3c/wai-quick-start/pull/393

Thanks for this important contribution!

**Comment by frirasyidi** [comment]
> Hi @frirasyidi
> 
> I have finished reviewing your translation: I have added comments in the Pull Request for your consideration: see [w3c/wai-quick-start#393](https://github.com/w3c/wai-quick-start/pull/393)
> 
> Thanks for this important contribution!

Yes, I have replied and make necessary changes. Some also requires confirmation from your side before I made the changes, please take a look. Thank you!

**Comment by remibetin** [comment]
This translation is now ready to publish!

**Comment by remibetin** [comment]
This translation has been published today 🚀 Thank you @frirasyidi !

See https://www.w3.org/WAI/tips/id
