### ISSUE TITLE
Bahasa Indonesia - Introduction to Web Accessibility

### ISSUE THREAD

**Issue by frirasyidi** [w3c/wai-translations#132]
I would like to update the Bahasa Indonesia translation to meet update on 2023 Nov 20 of  the following resource:
- Page URL:https://www.w3.org/WAI/fundamentals/accessibility-intro

I have read the information on Translating WAI Documents at https://www.w3.org/WAI/about/translating/

I will wait for confirmation that the resource is ready for translation.

**Comment by remibetin** [comment]
Hi @frirasyidi,

Thank you, I confirm you can proceed with this translation update! 

To help you, here are some ways to check what needs update:
- [GitHub diff](https://github.com/w3c/wai-intro-accessibility/compare/gh-pages@%7B2021-05-08%7D%E2%80%A6gh-pages@%7B2023-11-23%7D) between the Indonesian translation date (2021-05-08) and the resource last update. Use the "Files changes" tab and look for `content/index.md`
- [Changelog](https://www.w3.org/WAI/fundamentals/accessibility-intro/changelog/) on WAI website.

You've declared your intent to translate/update other resources. Here is a suggested approach for your contributions:
1. Update "Introduction to Web Accessibility" translation
2. Update "W3C Accessibility Standards Overview" translation: https://github.com/w3c/wai-translations/issues/133
2. Translate "Tips for Getting Started": https://github.com/w3c/wai-translations/issues/130

**Comment by frirasyidi** [comment]
@remibetin the translation is ready for review: https://github.com/w3c/wai-intro-accessibility/pull/84

**Comment by remibetin** [comment]
This PR is indeed ready for review! 🚀

**Comment by remibetin** [comment]
This translation is now ready to publish! 🚀

**Comment by remibetin** [comment]
This translation update has been published today 🚀 Thank you @frirasyidi !

See https://www.w3.org/WAI/fundamentals/accessibility-intro/id
