### ISSUE TITLE
Bahasa Indonesia - W3C Accessibility Standards Overview

### ISSUE THREAD

**Issue by frirasyidi** [w3c/wai-translations#133]
I would like to update the Bahasa Indonesia translation to meet its 2022-06-29 update of  the following resource:
- Page URL: https://www.w3.org/WAI/standards-guidelines/id

I have read the information on Translating WAI Documents at https://www.w3.org/WAI/about/translating/

I will wait for confirmation that the resource is ready for translation.

**Comment by remibetin** [comment]
@frirasyidi Thank you, you can proceed with this translation update! 

You can take a look at the [GitHub diff](https://github.com/w3c/wai-std-gl-overview/compare/master@%7B2021-05-08%7D%E2%80%A6master@%7B2023-09-29%7D) between the Indonesian translation date (2021-05-08) and the resource last update. Use the "Files changes" tab and look for `content/index.md`

**Comment by frirasyidi** [comment]
> I suggest you update this translation after https://github.com/w3c/wai-translations/issues/132 and before https://github.com/w3c/wai-translations/issues/130

Noted @remibetin, will do as you suggest.

**Comment by frirasyidi** [comment]
@remibetin this is ready for review: https://github.com/w3c/wai-std-gl-overview/pull/72

**Comment by remibetin** [comment]
This PR is ready for review! 🚀

**Comment by remibetin** [comment]
This translation is now ready to publish 🚀 , thank you @frirasyidi!

**Comment by remibetin** [comment]
This translation update has been published today 🚀 Thank you @frirasyidi!

See https://www.w3.org/WAI/standards-guidelines/id
