### ISSUE TITLE
Bahasa Indonesia - An alt Decision Tree

### ISSUE THREAD

**Issue by frirasyidi** [w3c/wai-translations#145]
I would like to  translate into Bahasa Indonesia  the following resource:
- Page URL: https://www.w3.org/WAI/tutorials/images/decision-tree/

I have read the information on Translating WAI Documents at https://www.w3.org/WAI/about/translating/

I will wait for confirmation that the resource is ready for translation.

**Comment by frirasyidi** [comment]
@remibetin can I start working on this translation?

**Comment by frirasyidi** [comment]
@remibetin I just realised that the "alt decision tree" page is part of "tutorial" section. I think I would like to tackle all together instead of just the page.

I will work on them in the same PR for now, but let me know if you prefer otherwise.

**Comment by remibetin** [comment]
Hi Fri,

_Tutorials_ resources are in the process of being updated. Completion is expected in 2024.
Therefore, we recommend to only translate the _Alt decision tree_ page for now.

**Comment by frirasyidi** [comment]
@remibetin noted, on that case the translation is ready to review except for the footer part which I've noted in the PR: https://github.com/w3c/wai-tutorials/pull/737

**Comment by remibetin** [comment]
This translation is ready for review! 🎉

Reviewers are welcome to add their comments and collaborate with the translator in the related Pull Requests:
- Page content: https://github.com/w3c/wai-tutorials/pull/737
- UI terms used in the footer: https://github.com/w3c/wai-website-data/pull/116

**Comment by remibetin** [comment]
Hi @frirasyidi 

I have added a comment in the Pull Request, see https://github.com/w3c/wai-tutorials/pull/737

We might be able to publish this translation very soon afterwards: thanks!

**Comment by frirasyidi** [comment]
@remibetin I have updated the translation based on your feedback.

**Comment by remibetin** [comment]
This translation is now ready to publish 🚀 , thanks @frirasyidi!

**Comment by remibetin** [comment]
This translation has been published today 🚀 Thank you @frirasyidi!

See https://www.w3.org/WAI/tutorials/images/decision-tree/id
