### ISSUE TITLE
Bahasa Indonesia - Accessibility Principles

### ISSUE THREAD

**Issue by frirasyidi** [w3c/wai-translations#146]
I would like to  translate into Bahasa Indonesia  the following resource:
- Page URL: https://www.w3.org/WAI/fundamentals/accessibility-principles/

I have read the information on Translating WAI Documents at https://www.w3.org/WAI/about/translating/

I will wait for confirmation that the resource is ready for translation.

**Comment by remibetin** [comment]
Hi @frirasyidi 

I may need to make small updates to this resource. Let me check on that, and get back to you.

**Comment by remibetin** [comment]
@frirasyidi This issue seems redundant with https://github.com/w3c/wai-translations/issues/72 Is not it?

**Comment by frirasyidi** [comment]
Ah you are correct. I was just blindly following the priority list from top to bottom in the translation page. I am sorry, that was my mistake. Thanks for notifying and noticing.
