### ISSUE TITLE
Add WAI-CooP ack

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-translations#152]
Hi @remibetin

For pages that you created or updated, we want to add acknowledgment for WAI-CooP project.

Depending on the page, it could be like https://www.w3.org/WAI/policies/#wai-page-footer
> Updated as part of the [WAI-Guide project](https://www.w3.org/WAI/about/projects/wai-guide), co-funded by the European Commission.

or like https://www.w3.org/WAI/standards-guidelines/atag/no-code/#wai-site-footer

> Developed as part of the [WAI-Guide project](https://www.w3.org/WAI/about/projects/wai-guide), co-funded by the European Commission.

## OK as is:
* https://www.w3.org/WAI/translations/

## Add updated:
Add _(after "Developed with input from the Education and Outreach Working Group (EOWG)." in same paragraph when that sentences exists)_:
> Updated as part of the <a href="https://www.w3.org/WAI/expand-access/">WAI Expanding Access</a> and <a href="https://www.w3.org/WAI/about/projects/wai-core-ford/">WAI-Core Ford</a> projects, funded by the Ford Foundation; and the <a href="https://www.w3.org/WAI/about/projects/wai-coop/">WAI-Coop</a> project, co-funded by the European Commission.

to:
* https://www.w3.org/WAI/standards-guidelines/wcag/translations/

## Add created or updated as appropriate
to:
* https://www.w3.org/WAI/about/translating/ and all the subpages
* the README of this repo

**Comment by remibetin** [comment]
> https://www.w3.org/WAI/standards-guidelines/wcag/translations/

See https://github.com/w3c/wai-intro-wcag/pull/261

**Comment by remibetin** [comment]
@shawna-slh @iadawn Is it necessary to add this Ack in resources I slightly changed: to make them ready for translations, update links, etc.?

Examples:
https://github.com/w3c/wai-quick-start/pull/390
[https://github.com/w3c/wai-intro-atag/pull/11/](https://github.com/w3c/wai-intro-atag/pull/11/files#diff-a4f40b84fbcf1a7939d596dca4939bbae6e56c05ad06a62b719b42693a9baf07)

**Comment by remibetin** [comment]
Completed
