### ISSUE TITLE
[low] All WAI Translations -  don't include video subtitles listing if the page the video is on is translated

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-translations#158]
Summary: When the resource page is translated, do not also have the video subtitles listing.

Ref: [All WAI Translation](https://www.w3.org/WAI/translations/)

The resource that we have the most translations of is https://www.w3.org/WAI/videos/standards-and-benefits/
All the translated versions of that page also have video subtitles in the language. Generally, when a page with a video is translated, the video will have the subtitles translated. (a few pages were we added the video, we need to update to include the subtitles)

We also have subtitles for that video in an additional ~7 languages (i.e., the rest of the pages is not translated).

The [All WAI Translations page](https://www.w3.org/WAI/translations/) now includes the subtitle languages in the main languages listing. (thanks Rémi !)

I'm now thinking we want to tweak that a bit.

For languages that have only video subtitles translated, I think it's good as is. e.g., https://www.w3.org/WAI/translations/#telugu

For languages that have the web page that houses the video translated (as well as the subtitles), I'm thinking that we do not want a separate listing for the video subtitles. e.g., https://www.w3.org/WAI/translations/#nederlands-dutch would have only "Video-introductie over Web-toegankelijkheid en W3C-standaarden" and not also the "Video Subtitles".

Do you agree this approach is good usability? Any reason not to?

**Comment by shawna-slh** [comment]
@remibetin O. is passing on this, so you can take it on whenever higher priorities are done.

**Comment by remibetin** [comment]
@shawna-slh Done!
