### ISSUE TITLE
[German] An alt Decision Tree

### ISSUE THREAD

**Issue by alexejrotar** [w3c/wai-translations#159]
Pull Requests:
- Translated page content: https://github.com/w3c/wai-tutorials/pull/741
- Translated terms for footer: https://github.com/w3c/wai-website-data/pull/119

---

I would like to  translate into German  the following resource:
- Page URL: https://www.w3.org/WAI/tutorials/images/decision-tree/
- Link to original file in GitHub: [https://github.com/w3c/wai-tutorials/edit/master-2.0/content/images/decision-tree.md](https://github.com/w3c/wai-tutorials/edit/master-2.0/content/images/decision-tree.md)

I have read the information on Translating WAI Documents at https://www.w3.org/WAI/about/translating/

I will wait for confirmation that the resource is ready for translation.

https://github.com/w3c/wai-translations/labels/initial-translation

**Comment by remibetin** [comment]
Hi @alexejrotar,

Thank you very much for volunteering to translate this resource into German!

You can proceed with this translation.

Please note that additional translation instructions must be followed to translate the footer: see https://github.com/w3c/wai-tutorials#translation-notes

**Comment by alexejrotar** [comment]
Just created a PR: [#741](https://github.com/w3c/wai-tutorials/pull/741).

**Comment by remibetin** [comment]
This translation is ready for review! 🎉

Reviewers are welcome to add their comments and collaborate with the translator in the related Pull Request: https://github.com/w3c/wai-tutorials/pull/741

**Comment by D-oro** [comment]
Hi, I'm a new reviewer and native German speaker. I read and followed the guidance and as agreed with @remibetin will review this before the 31st of March (likely before then).

**Comment by remibetin** [comment]
This translation is now ready to publish!

**Comment by remibetin** [comment]
This translation has been published today 🚀 Thank you @alexejrotar @D-oro @j9t!

See https://www.w3.org/WAI/tutorials/images/decision-tree/de
