### ISSUE TITLE
[Japanese] An alt Decision Tree

### ISSUE THREAD

**Issue by hiroya-uga** [w3c/wai-translations#166]
I would like to  translate into Japanese  the following resource:
- Page URL: https://www.w3.org/WAI/tutorials/images/decision-tree/
- Link to original file in GitHub: [https://github.com/w3c/wai-tutorials/edit/master-2.0/content/images/decision-tree.md](https://github.com/w3c/wai-tutorials/edit/master-2.0/content/images/decision-tree.md)

I have read the information on Translating WAI Documents at https://www.w3.org/WAI/about/translating/

I will wait for confirmation that the resource is ready for translation.

https://github.com/w3c/wai-translations/labels/initial-translation

**Comment by remibetin** [comment]
Hi @hiroya-uga,

Thank you very much for volunteering to translate this resource into Japanese!

I confirm that this resource is ready for translation: you can proceed.

**Comment by hiroya-uga** [comment]
@remibetin Thank you!

Just to confirm, when making the following Japanese translation:
https://github.com/w3c/wai-tutorials/edit/master-2.0/content/images/decion-tree.md
I should create the following file:
https://github.com/w3c/wai-tutorials/edit/master-2.0/content/images/decion-tree.ja.md

Is this correct?

**Comment by remibetin** [comment]
@hiroya-uga Exactly!

I encourage you to read the following guides when translating a document:
- https://www.w3.org/WAI/about/translating/guides/new-translation/
- https://www.w3.org/WAI/about/translating/guides/translation-guidance/

**Comment by hiroya-uga** [comment]
@remibetin Thank you! I'm reading these documents! 
I appreciate you notice me!

**Comment by remibetin** [comment]
This translation is ready for review! 🎉

Reviewers are welcome to add their comments and collaborate with the translator in the related Pull Request: https://github.com/w3c/wai-tutorials/pull/752

**Comment by remibetin** [comment]
This translation is now ready to publish 🚀

**Comment by remibetin** [comment]
This translation has been published today 🚀 Thank you @hiroya-uga @momdo!

See https://www.w3.org/WAI/tutorials/images/decision-tree/ja
