### ISSUE TITLE
[Japanese] Update Video Introduction to Web Accessibility

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-translations#168]
### Direct links

- Japanese translation: https://www.w3.org/WAI/videos/standards-and-benefits/ja
- Original English version: https://www.w3.org/WAI/videos/standards-and-benefits
- Link to file: https://github.com/w3c/wai-video-standards-and-benefits/blob/master/content/index.ja.md

### Context

- The original resource has been updated in May 2021, after the Japanese initial translation.
- Some wording is still in English in the Japanese translation

### Updates needed

Original:
> On a W3C server — video (file format: MP4, file size: 28MB), ...

Current translation
> W3C — MP4、28MB, ...

- [x] Need translation of: "On a W3C server"
- [x] Need translation of: "video (file format: MP4, file size: 28MB)"

---

Original:
> If you want examples of videos with audio description... and select “Enable Audio Description”.

Current Translation:
> 音声描写の一例を希望する際は、ウェブアクセシビリティの観点から ー 音声 (YouTubeプレイリスト)、ウェブアクセシビリティの観点から (英語版)、”音声描写を有効化するために”を参照下さい

- [x] Add user interface phrase in English: (<span lang="en">“Enable Audio Description”</span>)
(if you're interested, rationale is [here](https://github.com/w3c/wai-translations/issues/170))

---

Original:

```
We welcome additional translations. If you translate the [VTT file](https://www.w3.org/WAI/wai-videos/video-introduction/video-introduction.en.vtt), please send it to <public-wai-translations@w3.org>. If you might want to translate this entire web page or others, please see [[Translating WAI Resources]](/about/translating/).
```

Current Translation:

```
W3Cは他言語の翻訳を歓迎します。[VTT file](https://www.w3.org/WAI/wai-videos/video-introduction/video-introduction.en.vtt)の翻訳物は <public-wai-translations@w3.org>までお送り下さい。本ウェブページ全体や他資料を翻訳ご希望の方は[[Translating WAI Resources](https://www.w3.org/WAI/about/translating/)をご覧ください。
```

- [x] Need translation of "Translating WAI Resources" page title
- [x] Need double-brackets closing

---

- [x] Need translation of new sentence added to the footer in 2021:

```markdown
 Video clips developed with support from the <a href="https://www.w3.org/WAI/DEV/">WAI-DEV project</a>, co-funded by the European Commission. Translations managed with support from the <a href="https://www.w3.org/WAI/expand-access/">WAI Expanding Access project</a>, funded by the Ford Foundation.</p>
```

---

Issues moved to https://github.com/w3c/wai-translations/issues/169 :

<strike>
<new one added 26 March>

- [ ] Change translation to just say 'This page in:' (not include "Japanese")

```
- en: 'This&nbsp;page&nbsp;in:'   # "This page in:" with &nbsp; between words to avoid line breaks (for top "This page in: English...")
  ja: '本ページは日本語表記です'
```

Original:
```en: 'This volunteer translation might not accurately reflect the intentions of the <a href="$1">English original</a>.'```

Current translation:
```ja: 'ボランタリーの本翻訳は、英語原文を正確に反映していない場合があります('```

- [x] Please confirm if this is correct:

```ja: 'ボランタリーの本翻訳は、英語原文を正確に反映していない場合があります</a>'```
</strike>

**Comment by remibetin** [comment]
@hiroya-uga Would you be interested in updating this translation according to the issue description?

**Comment by hiroya-uga** [comment]
I would like to translate into Japanese the this resource!

**Comment by remibetin** [comment]
Thanks @hiroya-uga! You can proceed with this translation update. Please feel free to suggest further updates to this translation if you consider it necessary.

**Comment by hiroya-uga** [comment]
@remibetin The sentence makes me confusing...

> Or you can select one of the videos on the [Web Accessibility Perspectives web page](https://www.w3.org/WAI/perspective-videos/) and select “Enable Audio Description”.

I guess it means this flow:

1. Open the page
2. Play one of the videos
3. Select "Enable Audio Description"

But there is not "Enable Audio Description" button.

**Comment by remibetin** [comment]
Hi @hiroya-uga

Thanks very much for your work, and for these relevant questions!

> 1️⃣ The actual titles of the videos on YouTube are in English, so I think it's better not to translate them. What do you think?

We generally want all the content of a translated page to be in the target language, so I think it is best to translate the titles into Japanese.

> I guess it means this flow:
> - Open the page
> - Play one of the videos
> - Select "Enable Audio Description"
> - But there is not "Enable Audio Description" button.

The flow is as follows:
1. Open the page "Web Accessibility Perspectives"
2. Choose a video by clicking on the corresponding link/image.
3. On the destination page, click on "Enable Audio Description"
4. Play the video

The button is just below the video player, see https://www.w3.org/WAI/perspective-videos/keyboard/ for example.

**Comment by hiroya-uga** [comment]
@remibetin Thank you for answering!

> We generally want all the content of a translated page to be in the target language, so I think it is best to translate the titles into Japanese.

I see. but I might be confused if the link text in Japanese is linked to English page...
Of course I follow tradition!

> The flow is as follows:

I understand perfectly! Thank you!!

**Comment by remibetin** [comment]
@hiroya-uga I confirm that we can keep https://github.com/w3c/wai-video-standards-and-benefits/pull/130 (the broader update). Thanks for this!

@yonaomi, who did the initial translation, has agreed to review your proposed changes! I will let you work together in the Pull Request.

**Comment by remibetin** [comment]
This updated translation has been published today 🚀 Thank you @hiroya-uga, @takuan517 & @momdo!

See https://www.w3.org/WAI/videos/standards-and-benefits/ja

cc @yonaomi
