### ISSUE TITLE
[Japanese] Update UI Terms

### ISSUE THREAD

**Issue by remibetin** [w3c/wai-translations#169]
- [x] Change translation to just say 'This page in:' (not include "Japanese")

```
- en: 'This&nbsp;page&nbsp;in:'   # "This page in:" with &nbsp; between words to avoid line breaks (for top "This page in: English...")
  ja: '本ページは日本語表記です'
```

- [x] Check if the current translation of "This volunteer translation might not accurately reflect the intentions of the English original" is correct

``` 
- en: 'This volunteer translation might not accurately reflect the intentions of the <a href="$1">English original</a>.'
  ja: 'ボランタリーの本翻訳は、英語原文 <a href="$1">を正確に反映していない場合があります</a>'
```

**Comment by remibetin** [comment]
@hiroya-uga Would you update this translation, either in [your existing PR](https://github.com/w3c/wai-website-data/pull/124) or in a new one? Thank you!

**Comment by hiroya-uga** [comment]
@remibetin I did it!
But, a direct translation would be uncomfortable, so I changed words and separated sentences to make it easier to understand.

> "This page in:" 

→ 翻訳：（"translation:"）

> This volunteer translation might not accurately reflect the intentions of the <a href="$1">English original</a>.

→ こちらはボランティアによって翻訳されたものです。<a href="$1">原文（英語）</a>の内容が正確に反映されていない可能性があります。（This is a translation by a volunteer. It may not accurately reflect the content of <a href="$1">the original (English)</a>.）

------

I have a question.

Is `hreflang="en"` unnecessary for the `a` element?

Thank you!

**Comment by remibetin** [comment]
@hiroya-uga 

> But, a direct translation would be uncomfortable, so I changed words to make it easier to understand. Is this a "change or adapt"?

For this UI term, this is fine.

> And I have a question. Is hreflang="en" unnecessary for the a element?

Good question. I have opened an issue for that: https://github.com/w3c/wai-translations/issues/177

**Comment by remibetin** [comment]
@hiroya-uga Thanks a lot for your help! We have published the updates today!
