### ISSUE TITLE
List of languages always visible top right on desktop

### ISSUE THREAD

**Issue by yatil** [w3c/wai-translations#17]
> Straw proposal for if the decision is that on "desktop" the list is always visible top right:

While I'm generally a fan of having the full list of languages displayed on the top right, we have to consider that the “jump to main content” link is currently right aligned.

That means, depending on the languages available, the link would change position.

Having only the icon for changing languages (accompanied by text) would mean a more consistent placement of the “jump to main content” link.

**Comment by r12a** [comment]
... unless the languages appeared to the left of the 'jump to' link, right?  I think that's what i would do (using flexbox).

**Comment by slhenry** [comment]
To clarify: "Skip to Content" would be in the same line of text. If the list of languages is short, it would be further right; if the list is long, it could be closer to center or even left.

> Having only the icon for changing languages (accompanied by text) would mean a more consistent placement of the “jump to main content” link.

Consistent position of the "Skip to Content" link seems very minor compared to the strong reasons for having the languages always visible: pros & cons at [Always visible vs. select](https://www.w3.org/wiki/WAI_Translations#Always_visible_vs._select); "using a pulldown [or other] to select languages should be avoided whenever possible" and "I strongly recommend using a list of links" &mdash; [r12a](https://github.com/w3c/wai-translations/issues/6)

I think the "Skip to Content" will mostly be used by:
* screen readers users -- who mostly won't know or care that it's visually is in different position in the line
* non-mouse users -- who probably really want it to be the first item they get to

Maybe I'm missing some important &/or common user scenarios?

**Comment by yatil** [comment]
> ... unless the languages appeared to the left of the 'jump to' link, right? I think that's what i would do (using flexbox).

Yes, we discussed this (separating the visual from the tab order), but I think it would not be something that would go well in the accessibility community as we preach that the tab order should go from top left to bottom right (in LTR languages).
