### ISSUE TITLE
[Mobile Accessibility at W3C] update translations

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-translations#173]
with these edits: https://github.com/w3c/wai-mobile/commits/master/index.md

| Language | Status | 
| --- | --- | 
| Arabic | ⏳ Date in footer to update |
| Czech |  ✅ Done |
| Spanish |  ✅ Done |
| French |  ✅ Done |
| Korean |  ✅ Done |
| Russian |  ✅ Done |
| Simplified Chinese | ✅ Done |

**Comment by remibetin** [comment]
The translations have all been updated since. Closing this issue.
