### ISSUE TITLE
Adding hreflang="en" when linking to the original version of the resource

### ISSUE THREAD

**Issue by remibetin** [w3c/wai-translations#177]
- [x] Consider if necessary or not. > Conclusion: not necessary if the value is not extracted and used.

Where? In the [translation disclaimer box](https://wai-website-theme.netlify.app/components/document-notes/translation/)

Current implementation example: https://www.w3.org/WAI/design-develop/es

Current:
```
This volunteer translation might not accurately reflect the intentions of the <a href="#">English original</a>.
```

To consider:
```
This volunteer translation might not accurately reflect the intentions of the <a href="#" hreflang="en">English original</a>.
```

Resource: https://www.w3.org/International/questions/qa-link-lang.en.html

**Comment by remibetin** [comment]
@r12a Any reason not to?

**Comment by r12a** [comment]
Since you are expressly pointing to an English version, and there will always be one, this seems a use case where it is less problematic.  How will the hreflang information be used, though?  It doesn't have any effect on anything unless you extract the value and do something with it.

**Comment by remibetin** [comment]
@r12a 

> How will the hreflang information be used, though? It doesn't have any effect on anything unless you extract the value and do something with it.

For now, no plan for the site to use this information.
