### ISSUE TITLE
[Polish] ATAG Overview

### ISSUE THREAD

**Issue by zwiastunsw** [w3c/wai-translations#178]
I would like to  translate into [language]  the following resource:
- Page URL: [https://www.w3.org/WAI/standards-guidelines/atag/](https://www.w3.org/WAI/standards-guidelines/atag/)

I have read the information on Translating WAI Documents at https://www.w3.org/WAI/about/translating/

I will wait for confirmation that the resource is ready for translation.

**Comment by remibetin** [comment]
This translation is ready for review! 🎉

Reviewers are welcome to add their comments and collaborate with the translator in the related Pull Request: https://github.com/w3c/wai-intro-atag/pull/66

Guidance: https://www.w3.org/WAI/about/translating/guides/review-translation/

**Comment by remibetin** [comment]
This translation is now ready to publish 🚀

**Comment by shawna-slh** [comment]
Thank you !

**Comment by zwiastunsw** [comment]
Thanks, but... Unfortunately, the pages do not display. Error 404 

- [Omówienie ATAG](https://www.w3.org/WAI/standards-guidelines/atag/pl)
- [ATAG w  skrócie](https://www.w3.org/WAI/standards-guidelines/atag/glance/pl)

**Comment by remibetin** [comment]
@zwiastunsw Indeed, we are investigating this.

**Comment by shawna-slh** [comment]
I think we found the issue. Will get it fixed today or soon.

**Comment by shawna-slh** [comment]
Fixed!
* https://wai-website.netlify.app/standards-guidelines/atag/pl
* https://wai-website.netlify.app/standards-guidelines/atag/glance/pl

**Comment by zwiastunsw** [comment]
Dziękuję!
