### ISSUE TITLE
[Polish] ATAG at Glance

### ISSUE THREAD

**Issue by zwiastunsw** [w3c/wai-translations#179]
I would like to  translate into [language]  the following resource:
- Page URL: [https://www.w3.org/WAI/standards-guidelines/atag/glance/](https://www.w3.org/WAI/standards-guidelines/atag/glance/)

I have read the information on Translating WAI Documents at https://www.w3.org/WAI/about/translating/

I will wait for confirmation that the resource is ready for translation.

**Comment by remibetin** [comment]
@zwiastunsw This resource is now ready for translation! You can now translate this resource located at https://github.com/w3c/wai-intro-atag/edit/master/content/glance.md

Thanks again!

**Comment by remibetin** [comment]
This translation is ready for review! 🎉

Reviewers are welcome to add their comments and collaborate with the translator in the related Pull Request: https://github.com/w3c/wai-intro-atag/pull/66

Guidance: https://www.w3.org/WAI/about/translating/guides/review-translation/

**Comment by remibetin** [comment]
This translation has been published 🚀 Thank you @zwiastunsw @humanthing-ltd!

See https://www.w3.org/WAI/standards-guidelines/atag/glance/pl
