### ISSUE TITLE
[Polish] UAAG Overview

### ISSUE THREAD

**Issue by zwiastunsw** [w3c/wai-translations#180]
I would like to  translate into [language]  the following resource:
- Page URL: [https://www.w3.org/WAI/standards-guidelines/uaag/](https://www.w3.org/WAI/standards-guidelines/uaag/)

I have read the information on Translating WAI Documents at https://www.w3.org/WAI/about/translating/

I will wait for confirmation that the resource is ready for translation.

**Comment by remibetin** [comment]
@zwiastunsw Thanks for volunteering to translate this resource. I need to apply some minor updates to the resource before you can start your translation.

Feel free to ping me if you do not hear from me by March 6.

**Comment by remibetin** [comment]
@zwiastunsw This resource is now ready for translation! You can now translate this resource located at https://github.com/w3c/wai-intro-uaag/edit/master/index.md

Thanks again!

**Comment by remibetin** [comment]
This translation is ready for review! 🎉

Reviewers are welcome to add their comments and collaborate with the translator in the related Pull Request: https://github.com/w3c/wai-intro-uaag/pull/13

Guidance: https://www.w3.org/WAI/about/translating/guides/review-translation/

**Comment by remibetin** [comment]
This translation has been published today 🚀 Thank you @zwiastunsw!

See https://www.w3.org/WAI/standards-guidelines/uaag/pl

**Comment by zwiastunsw** [comment]
Dziękuję!
