### ISSUE TITLE
[Polish] Website Accessibility Conformance Evaluation Methodology (WCAG-EM) 1.0

### ISSUE THREAD

**Issue by zwiastunsw** [w3c/wai-translations#182]
I would like to  translate into [language]  the following resource:
- Page URL: [https://www.w3.org/TR/WCAG-EM/](https://www.w3.org/TR/WCAG-EM/)

I have read the information on Translating WAI Documents at https://www.w3.org/WAI/about/translating/

I will wait for confirmation that the resource is ready for translation.

**Comment by remibetin** [comment]
@zwiastunsw _WCAG-EM_ is a "W3C Working Group Note" and therefore follows a different process: https://www.w3.org/Consortium/Translation/#how
