### ISSUE TITLE
[Korean] An Alt Decision Tree

### ISSUE THREAD

**Issue by hwahyeon** [w3c/wai-translations#191]
I would like to  translate into Korean  the following resource:
- Page URL: https://www.w3.org/WAI/tutorials/images/decision-tree/

I have read the information on Translating WAI Documents at https://www.w3.org/WAI/about/translating/

I will wait for confirmation that the resource is ready for translation.

**Comment by remibetin** [comment]
Thank you @hwahyeon for volunteering to translate the Alt Decision Tree into Korean!

You can proceed with this translation.

Please note that additional translation instructions must be followed to translate the footer: see https://github.com/w3c/wai-tutorials#translation-notes

**Comment by remibetin** [comment]
@hwahyeon I have reviewed your translation and added some comments in https://github.com/w3c/wai-tutorials/pull/761

**Comment by remibetin** [comment]
Thanks for your replies @hwahyeon! I will do some final checks next week. If you do not hear from me by Thursday 4 March, feel free to ping me.

**Comment by remibetin** [comment]
This translation is now ready to publish! 🚀

**Comment by remibetin** [comment]
This translation has been published today 🚀 Thank you @hwahyeon !

See https://www.w3.org/WAI/tutorials/images/decision-tree/ko

Please note that `ko` is the right language subtag to use for Korean. `kr` is the language subtag for [Kanuri](https://en.wikipedia.org/wiki/Kanuri_language) language. See registry here: https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry
