### ISSUE TITLE
[Polish] Evaluation Tools Overview

### ISSUE THREAD

**Issue by zwiastunsw** [w3c/wai-translations#193]
I would like to  translate into Polish  the following resource:
- Page URL: https://www.w3.org/WAI/test-evaluate/tools/
- Link to original file in GitHub: https://github.com/w3c/wai-website/blob/master/pages/test-eval/evaluation-tools/index.md

I have read the information on Translating WAI Documents at https://www.w3.org/WAI/about/translating/

I will wait for confirmation that the resource is ready for translation.

https://github.com/w3c/wai-translations/labels/initial-translation

**Comment by remibetin** [comment]
This translation has been published today 🚀 Thanks @zwiastunsw @viking-pl! 

See https://www.w3.org/WAI/test-evaluate/tools/pl
