### ISSUE TITLE
[Polish] Selecting Web Accessibility Evaluation Tools

### ISSUE THREAD

**Issue by zwiastunsw** [w3c/wai-translations#194]
I would like to  translate into Polish  the following resource:
- Page URL: https://www.w3.org/WAI/test-evaluate/tools/selecting/
- Link to original file in GitHub: [https://github.com/w3c/wai-selecting-eval-tools/edit/master/content/index.md](https://github.com/w3c/wai-selecting-eval-tools/edit/master/content/index.md)

I have read the information on Translating WAI Documents at https://www.w3.org/WAI/about/translating/

I will wait for confirmation that the resource is ready for translation.

https://github.com/w3c/wai-translations/labels/initial-translation

**Comment by remibetin** [comment]
@zwiastunsw This resource is now ready for translation. The file is now located at https://github.com/w3c/wai-website/edit/master/pages/test-evaluate/evaluation-tools/selecting-eval-tools.md

Please note that the resource includes a video, that is also used in [Evaluation Tools Overview](https://www.w3.org/WAI/test-evaluate/tools/). It would be great to have Polish subtitles available! If you are willing to do so, you can follow the related guidance at https://www.w3.org/WAI/about/translating/guides/video-subtitles/

Thanks again for your contributions! Feel free to contact me if you need any additional information or help.

**Comment by remibetin** [comment]
Hi @zwiastunsw,

I have checked the translation and added some comments for your consideration: https://github.com/w3c/wai-website/pull/561

Let me know if you need any further information or help.
