### ISSUE TITLE
[Polish] Introduction to Web Accessibility

### ISSUE THREAD

**Issue by zwiastunsw** [w3c/wai-translations#199]
I would like to  translate into Polish  the following resource:
- Page URL: https://www.w3.org/WAI/fundamentals/accessibility-intro/
- Link to original file in GitHub: [https://github.com/w3c/wai-intro-accessibility/edit/gh-pages/content/index.md](https://github.com/w3c/wai-intro-accessibility/edit/gh-pages/content/index.md)

I have read the information on Translating WAI Documents at https://www.w3.org/WAI/about/translating/

I will wait for confirmation that the resource is ready for translation.

https://github.com/w3c/wai-translations/labels/initial-translation

**Comment by remibetin** [comment]
Hi @zwiastunsw 

This ressource is indeed ready for translation. Thanks for your help!

**Comment by remibetin** [comment]
This translation is ready for review! 🎉

Reviewers are welcome to add their comments and collaborate with the translator in the related Pull Request: https://github.com/w3c/wai-intro-accessibility/pull/97

Guidance: https://www.w3.org/WAI/about/translating/guides/review-translation/

**Comment by remibetin** [comment]
This translation has been published today 🚀 Thank you @zwiastunsw @viking-pl!

See https://www.w3.org/WAI/fundamentals/accessibility-intro/pl
