### ISSUE TITLE
Translations thanks and link wording - in Translations Info box

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-translations#2]
At start of issue, straw proposal wording is:
> WAI thanks these translators, and welcomes other [translations](@@).

See latest wording proposal in [mock-up](https://w3c.github.io/wai-translation-playground/people-use-web/).

See the [Goals for translation info](https://www.w3.org/wiki/WAI_Translations#Translation_info_.2F_Disclaimer) and [Motivation and Recognition](https://www.w3.org/wiki/WAI_Translations#Motivation.2C_Recognition)

In your comment, you might want to quote the wording that you are commenting on, since the wording in the mock-up might change throughout the life of this issue.

**Comment by notabene** [comment]
> WAI thanks these translators, and welcomes other translations.

+1 for me, no change needed.
