### ISSUE TITLE
Page list options

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-translations#20]
Note: This is in addition to the full list of languages always at the very top right. (comment on that in https://github.com/w3c/wai-translations/issues/19 )

Change language of this page -- straw proposal 21 Nov:
* above h1, under breadcrumb; right aligned
* "Select Language" toggle, default list not shown
* toggle displays float-right box (which will cause h1 to wrap when displayed)
* lists only the languages this page is available in

More info in [Background](https://www.w3.org/wiki/WAI_Translations#21_November_Issues) and [Page list options](https://www.w3.org/wiki/WAI_Translations#Page_list_options)

**Comment by yatil** [comment]
Anywhere is better than now (no translations). I personally prefer 5 (unfortunately ruled out) before all the way on the top (also unfortunately ruled out) before 3 (above h1 - horizontal list) before 4 (below h1 - horizontal list). I’m not a fan of adding it to the breadcrumb area.

**Comment by slhenry** [comment]
> I personally prefer 5 ...I’m not a fan of adding it to the breadcrumb area.

The ruling out is based on the wrapping of the h1 even when the list is toggled off.

Is an in-between option do-able? That is, can the toggle be under the breadcrumb area yet above the h1 so **when the list is not shown, the toggle doesn't cause the h1 to wrap extra at all** (even if it does cause extra wrapping when the list is shown).

I added that as the new [first option - Option 0](https://www.w3.org/wiki/WAI_Translations#0._right_aligned.2C_above_h1.2C_under_breadcrumb_-_float-right_box_-_toggle_default_list_not_shown)  (so your comments still match the numbering :-)

**Comment by slhenry** [comment]
After further discussions, this approach rejected.
