### ISSUE TITLE
[Polish] Video Introduction to Web Accessibility and W3C Standards

### ISSUE THREAD

**Issue by zwiastunsw** [w3c/wai-translations#200]
I would like to  translate into Polish  the following resource:
- Page URL: https://www.w3.org/WAI/videos/standards-and-benefits/
- Link to original file in GitHub: [https://github.com/w3c/wai-video-standards-and-benefits/edit/master/content/index.md](https://github.com/w3c/wai-video-standards-and-benefits/edit/master/content/index.md)

I have read the information on Translating WAI Documents at https://www.w3.org/WAI/about/translating/

I will wait for confirmation that the resource is ready for translation.

https://github.com/w3c/wai-translations/labels/initial-translation

**Comment by remibetin** [comment]
@zwiastunsw Thank you! This resource is indeed ready for translation: you can proceed.

For subtitles, please follow this guide: https://www.w3.org/WAI/about/translating/guides/video-subtitles/

Please also read the specific Translations notes at https://github.com/w3c/wai-video-standards-and-benefits#readme

**Comment by remibetin** [comment]
This translation is ready for review! 🎉

Reviewers are welcome to add their comments and collaborate with the translator in the related Pull Requests: 
- Page content: https://github.com/w3c/wai-video-standards-and-benefits/pull/133
- Subtitles: https://github.com/w3c/wai-website-data/pull/137

Guidance: https://www.w3.org/WAI/about/translating/guides/review-translation/

**Comment by remibetin** [comment]
QA done: ✅
