### ISSUE TITLE
Translations priority order

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-translations#22]
Here's what I'm thinking for priority order to get "translations ready". (List can form straw proposal for EOWG input into actual translations priorities.)

* [ ] https://www.w3.org/WAI/videos/standards-and-benefits/ [need to decide if can default subtitle to that language]
* [ ] https://www.w3.org/WAI/fundamentals/accessibility-intro/
* [ ] https://www.w3.org/WAI/ [fyi, [Home Page what to translate](https://www.w3.org/wiki/WAI_Translations#Home_Page)]
* [ ] https://www.w3.org/WAI/standards-guidelines/wcag/
* [ ] https://www.w3.org/WAI/standards-guidelines/wcag/glance/
* [ ] https://www.w3.org/WAI/standards-guidelines/mobile/ [action shawn: check when content will be updated]
* [ ] https://www.w3.org/WAI/standards-guidelines/
* [ ] https://www.w3.org/WAI/design-develop/
* [ ] https://www.w3.org/WAI/test-evaluate/ (and excerpt pages https://www.w3.org/WAI/test-evaluate/tools/ & https://www.w3.org/WAI/test-evaluate/tools/ )
* [ ] https://www.w3.org/WAI/teach-advocate/
* [ ] https://www.w3.org/WAI/planning/
* [ ] https://www.w3.org/WAI/about/participating/ [action shawn: decide what to translate and what not]
* [ ] https://www.w3.org/WAI/about/ [action shawn: update content :-/]
* [ ] https://www.w3.org/WAI/roles/ (sub-pages are lower in the list)
* [ ] https://www.w3.org/WAI/fundamentals/accessibility-principles/
* [ ] https://www.w3.org/WAI/people-use-web/ & sub-pages
* [ ] https://www.w3.org/WAI/perspective-videos/ & sub-pages
* [ ] https://www.w3.org/WAI/teach-advocate/accessible-presentations/
* [ ] https://www.w3.org/WAI/business-case/
* [ ] https://www.w3.org/WAI/standards-guidelines/wcag/faq/
* [ ] https://www.w3.org/WAI/teach-advocate/contact-inaccessible-websites/
* [ ] https://www.w3.org/WAI/about/using-wai-material/
* [ ] https://www.w3.org/WAI/roles/ sub-pages
* [ ] https://www.w3.org/WAI/standards-guidelines/aria/ [this page needs love :-/]
* [ ] https://www.w3.org/WAI/ARIA/faq
* [ ] https://www.w3.org/WAI/fundamentals/components/
* [ ] https://www.w3.org/WAI/standards-guidelines/atag/
* [ ] https://www.w3.org/WAI/intro/atag-glance
* [ ] https://www.w3.org/WAI/standards-guidelines/uaag/
* [ ] https://www.w3.org/WAI/standards-guidelines/earl/
* [ ] https://www.w3.org/WAI/planning/interim-repairs/
* [ ] https://www.w3.org/WAI/planning-and-managing/ & 4 sub-pages
* [ ] https://www.w3.org/WAI/planning/org-policies/
* [ ] https://www.w3.org/WAI/planning/involving-users/
* [ ] https://www.w3.org/WAI/test-evaluate/involving-users/
* [ ] https://www.w3.org/WAI/tips/writing/
* [ ] https://www.w3.org/WAI/tips/designing/
* [ ] https://www.w3.org/WAI/tips/developing/
* [ ] https://www.w3.org/WAI/tutorials/page-structure/
* [ ] https://www.w3.org/WAI/tutorials/menus/
* [ ] https://www.w3.org/WAI/tutorials/images/
* [ ] https://www.w3.org/WAI/tutorials/tables/
* [ ] https://www.w3.org/WAI/tutorials/forms/
* [ ] https://www.w3.org/WAI/tutorials/carousels/
* [ ] https://www.w3.org/WAI/tutorials/
* [ ] https://www.w3.org/WAI/eval/selectingtools
* [ ] https://www.w3.org/WAI/test-evaluate/conformance/wcag-em/
* [ ] https://www.w3.org/WAI/training/Overview & sub-pages
* [ ] https://www.w3.org/WAI/standards-guidelines/w3c-process/
* [ ] https://www.w3.org/WAI/standards-guidelines/linking/
* [ ] https://www.w3.org/WAI/about/contacting/
* [ ] https://www.w3.org/WAI/test-evaluate/preliminary/ **after revision**
* [ ] https://www.w3.org/WAI/fundamentals/accessibility-usability-inclusion/ **after revision**
* [ ] https://www.w3.org/WAI/Policy/harmon **after revision**

_/me thinks that's all, but cannot promise didn't miss some :-/_

**Comment by yatil** [comment]
Oh, I should have been clearer and say that this work is done by resource (we don’t want the overhead to keep track of what pages in resources are ready to translate and it is easier to do it in one fellow swoop). Looks like pretty much everything has priority. :-)

**Comment by cousquer** [comment]
👋 @yatil , I can give you a hand on french 🇫🇷 , if you want. 
Before I need to have a close look at [w3c translation policy](https://www.w3.org/WAI/about/translating/#w3c-translation-policy)

**Comment by yatil** [comment]
@cousquer That would be wonderful. We’re about to reach out to translation beta testers. @notabene has done some French for us, and it would be great to have a team working on it. :) (@slhenry ^^ FYI)

**Comment by cousquer** [comment]
ça marche! 👍 😉

**Comment by notabene** [comment]
Or “Alles gut”, as they say at WAI. 😄

**Comment by cousquer** [comment]
👀 I'm looking closely also at [WAI_Translations](https://www.w3.org/wiki/WAI_Translations#Home_Page)

**Comment by slhenry** [comment]
clearer issue here: https://github.com/w3c/wai-translations/issues/31
