### ISSUE TITLE
[Polish] An alt Decision Tree

### ISSUE THREAD

**Issue by zwiastunsw** [w3c/wai-translations#221]
I would like to  translate into Polish  the following resource:
- Page URL: https://www.w3.org/WAI/tutorials/images/decision-tree/
- Link to original file in GitHub: [https://github.com/w3c/wai-tutorials/edit/master-2.0/content/images/decision-tree.md](https://github.com/w3c/wai-tutorials/edit/master-2.0/content/images/decision-tree.md)

I have read the information on Translating WAI Documents at https://www.w3.org/WAI/about/translating/

I will wait for confirmation that the resource is ready for translation.

https://github.com/w3c/wai-translations/labels/initial-translation

**Comment by remibetin** [comment]
@zwiastunsw This resource is indeed ready for translation: thanks for volunteering!

Please note that additional translation instructions must be followed to translate the footer: see https://github.com/w3c/wai-tutorials#translation-notes

**Comment by remibetin** [comment]
This translation is ready for review! 🎉

Reviewers are welcome to add their comments and collaborate with the translator in the related Pull Request: https://github.com/w3c/wai-tutorials/pull/786

Guidance: https://www.w3.org/WAI/about/translating/guides/review-translation/
