### ISSUE TITLE
[Japanese] WCAG 2 Overview

### ISSUE THREAD

**Issue by MakotoUeki** [w3c/wai-translations#231]
I would like to  translate into [Japanese]  the following resource:
- Page URL: [https://www.w3.org/WAI/standards-guidelines/wcag/](https://www.w3.org/WAI/standards-guidelines/wcag/)

I have read the information on Translating WAI Documents at https://www.w3.org/WAI/about/translating/

I will wait for confirmation that the resource is ready for translation.

**Comment by remibetin** [comment]
This translation has been published today 🚀 Thank you @MakotoUeki!

See https://www.w3.org/WAI/standards-guidelines/wcag/ja

**Comment by MakotoUeki** [comment]
Thank you very much for your help. I will do it right next time!

Makoto

2024年4月9日(火) 0:59 Rémi Bétin ***@***.***>:
