### ISSUE TITLE
[Polish] Report Tool

### ISSUE THREAD

**Issue by jakub-stanczykowski** [w3c/wai-translations#238]
I would like to  translate into Polish  the following resource:
- Page URL: https://www.w3.org/WAI/eval/report-tool/
- Link to original file in GitHub: [https://github.com/w3c/wai-website/edit/master/index.md](https://github.com/w3c/wai-website/edit/master/index.md)

I have read the information on Translating WAI Documents at https://www.w3.org/WAI/about/translating/

I will wait for confirmation that the resource is ready for translation.

https://github.com/w3c/wai-translations/labels/initial-translation

**Comment by zwiastunsw** [comment]
@jakub-stanczykowski , @remibetin : this resource was translated: https://github.com/w3c/wai-wcag-em-report-tool/pull/146 and  to complete the approval process

**Comment by zwiastunsw** [comment]
@remibetin: any response?

**Comment by remibetin** [comment]
Hi @jakub-stanczykowski 

Sorry for the delay in replying. The Polish translation of the WCAG-EM Report Tool was indeed published last month.

Are you still interesting in translating or reviewing other WAI resources?
