### ISSUE TITLE
Page with all translations

### ISSUE THREAD

**Issue by yatil** [w3c/wai-translations#24]
**VERY EARLY THINKING**

First attempt to have something to look at: https://w3c.github.io/wai-translation-playground/translations/

Still needs:

- [x] A way to filter by URL
- [x] Maybe better organization
- [x] Place in navigation (I don't think we should put it under roles as that is confusing. If it said “translators” I would find accessibility guidance for translators there. If it says ”translations”, that is not a role. If it says “non-english speaking people”, how would they find it if it isn’t available in their language? We have it linked from the top-right of every page, I think that is sufficient.)

**Comment by yatil** [comment]
from: https://www.w3.org/wiki/WAI_Translations#User_experience_for_the_list_of_resources_in_language

"All Translations" link gives users the following ''(which can be on multiple pages or one page depending on implementation considerations)'':

1. A list of all languages in which WAI has translations. The full list is visible by default (as opposed to the user needing to select to see the list). It can be collapsible. Selecting a language provides 2:
2. A list of all WAI pages available in XYZ language.<br>''Note:''
  * [ ] Ideally it is easy to provide a link to the specific language list of WAI resources to others.
  * [ ] Ideally organized as the site map is – though low priority for now.
  * [ ] We might want to include the summary with the page titles – low priority for now.
  * [ ] We might want to list the Translators names – low priority for now.

**Comment by slhenry** [comment]
> Ideally it is easy to provide a link to the specific language list of WAI resources to others.

@yatil, what do you think of adding the "SHARE" link for each language?

**Comment by slhenry** [comment]
I think first put the language in it's own language, then in English in parenthesis after. e.g.,

> Deutsch (German)

**Comment by yatil** [comment]
> @yatil, what do you think of adding the "SHARE" link for each language?

We don’t yet have that component in the redesign. (It was never designed and we never agreed on an approach.)

**Comment by yatil** [comment]
Preview here: https://deploy-preview-125--wai-website.netlify.com/translations/

I’d recommend opening another issue for further features.
