### ISSUE TITLE
[Spanish] WCAG 2 Overview

### ISSUE THREAD

**Issue by cmuncharaz** [w3c/wai-translations#243]
I would like to update the Spanish translation of  the following resource:

- Page URL: https://www.w3.org/WAI/standards-guidelines/wcag/es

I have read the information on Translating WAI Documents at https://www.w3.org/WAI/about/translating/

I will wait for confirmation that the resource is ready for translation.

**Comment by remibetin** [comment]
Thank you @cmuncharaz! You can proceed.

**Comment by cmuncharaz** [comment]
PR ready for review: [Spanish translation update](https://github.com/w3c/wai-intro-wcag/pull/288).

**Comment by remibetin** [comment]
This translation update has been published today 🚀 Thank you @cmuncharaz!

See https://www.w3.org/WAI/standards-guidelines/es
