### ISSUE TITLE
[Simplified Chinese] Developing for Web Accessibility – Tips for Getting Started

### ISSUE THREAD

**Issue by heybran** [w3c/wai-translations#248]
### Page URL

https://www.w3.org/WAI/tips/developing/

### Instructions

- [X] I have read the information on [Translating WAI Documents](https://www.w3.org/WAI/about/translating/)
- [X] Before starting the translation, I will wait for confirmation that the resource is ready for translation.

### Link to original file in GitHub

https://github.com/w3c/wai-website/edit/main/collections/_tips/developing.md

**Comment by remibetin** [comment]
Hi @heybran,

Thanks for volunteering to translate "Tips for Developing for Web Accessibility" into Simplified Chinese: we welcome new translations and translation updates!

If this is your first time volunteering to translate a WAI resource, would you please send an email to [group-wai-translations@w3.org](mailto:group-wai-translations@w3.org), to express your interest in joining the WAI translator volunteers community? I am sorry if I missed a communication.

After this initial contact, I can guide you through the next steps.

**Comment by heybran** [comment]
Hi @remibetin,

I have sent the email just now. Thanks for reminding me that.

**Comment by remibetin** [comment]
Hi @heybran,

Thank you. We have not received the email just yet. Could you check if you have received an automatic reply?

**Comment by heybran** [comment]
Hi @remibetin,

I did received an automatic reply before and clicked the review link to confirm that. I try to click the review link again now, but it seems to me it has expired. What should I do now?

> ID not found
Error: There is no message with id: 55c5b****
Please make sure you have cut and pasted the URI correctly.

<img width="577" alt="image" src="https://github.com/user-attachments/assets/abbc0fef-4380-4548-8796-c941507fe03f">

**Comment by heybran** [comment]
Hi @remibetin,

Kindly note that PR is ready for review: https://github.com/w3c/wai-website/pull/919

I will work on fixes if anything needs to be changed in this PR. Meanwhile, I will find time to translate other documentations to Simplified Chinese.

**Comment by remibetin** [comment]
Thanks very much @heybran!

This translation is now ready for review! 🎉

Reviewers are welcome to add their comments and collaborate with the translator in the related Pull Request: https://github.com/w3c/wai-website/pull/919

Guidance: https://www.w3.org/WAI/about/translating/reviewing/

**Comment by remibetin** [comment]
@heybran Thanks! I have reviewed your translation and added some comments to the Pull request.

**Comment by remibetin** [comment]
@heybran Thanks for the improvements. I have added two final comments:
- https://github.com/w3c/wai-website/pull/919#discussion_r1856418205
- https://github.com/w3c/wai-website/pull/919#discussion_r1856394269

**Comment by remibetin** [comment]
This translation has been published today 🚀 Thank you @heybran, @JinMokai and @ruoxiran !

See https://www.w3.org/WAI/tips/developing/zh-hans
