### ISSUE TITLE
[Simplified Chinese] Introduction to Web Accessibility

### ISSUE THREAD

**Issue by JinMokai** [w3c/wai-translations#254]
### Page URL

https://www.w3.org/WAI/fundamentals/accessibility-intro/zh-hans

### Instructions

- [X] I have read the information on [Translating WAI Documents](https://www.w3.org/WAI/about/translating/)
- [X] Before starting the translation, I will wait for confirmation that the resource is ready for translation.

### Link to original file in GitHub

https://github.com/w3c/wai-website/edit/main/pages/fundamentals/introduction/index.zh-hans.md

**Comment by remibetin** [comment]
Hi @JinMokai,

Thanks for volunteering. If this is your first time volunteering to translate a WAI resource, would you please send an email to [group-wai-translations@w3.org](mailto:group-wai-translations@w3.org), to express your interest in joining the WAI translator volunteers community? I am sorry if I missed a communication.

After this initial contact, I will guide you through the next steps.

**Comment by JinMokai** [comment]
@remibetin Thanks for the reply, I sent the email before I created this issues

**Comment by remibetin** [comment]
> Thanks for the reply, I sent the email before I created this issues

Thanks @JinMokai. However, we have not received it yet. You may have received an automatic reply asking you to confirm that you are the sender of the message. Would you please check your inbox or spam folder?

**Comment by JinMokai** [comment]
> Thanks @JinMokai. However, we have not received it yet. You may have received an automatic reply asking you to confirm that you are the sender of the message. Would you please check your inbox or spam folder?

![image](https://github.com/user-attachments/assets/bd0c9939-5b7c-4fb7-b20e-ba425ed513de)

I remember that I have sent the email and have clicked on the link in the email

**Comment by JinMokai** [comment]
> @JinMokai Unfortunately, I cannot find your email. Would you please send it again?很遗憾，我找不到您的电子邮件。请再次发送吗？

I just sent the email.
![image](https://github.com/user-attachments/assets/4a47c560-8af0-4bd8-b486-7a884024db37)

Come to think of it, I clicked on the link and chose the default option
It's probably because of this that you can't receive emails, I'm sorry about that!🤯

**Comment by remibetin** [comment]
@JinMokai Thanks. Messages from first-time posters could be delayed. I hope to receive your email in a few days.

I will send you an email.

**Comment by shawna-slh** [comment]
Hi @JinMokai and @remibetin Indeed the message was awaiting approval. I have approved it and it is now available to Rémi. :)

**Comment by JinMokai** [comment]
@remibetin I've finished the translation. Please review it.
If there are any problems, I'll change it as soon as I can, thank you very much!
resolves w3c/wai-website#930

**Comment by remibetin** [comment]
This translation update is ready for review! 🎉

Reviewers are welcome to add their comments and collaborate with the translator in the related Pull Request: https://github.com/w3c/wai-website/pull/930

Guidance: https://www.w3.org/WAI/about/translating/guides/review-translation/
