### ISSUE TITLE
[Simplified Chinese] W3C Accessibility Standards Overview

### ISSUE THREAD

**Issue by heybran** [w3c/wai-translations#255]
### Page URL

https://www.w3.org/WAI/standards-guidelines/zh-hans

### Instructions

- [X] I have read the information on [Translating WAI Documents](https://www.w3.org/WAI/about/translating/)
- [X] Before starting the translation, I will wait for confirmation that the resource is ready for translation.

### Link to original file in GitHub

https://github.com/w3c/wai-website/edit/main/pages/standards-guidelines/index.zh-hans.md

**Comment by remibetin** [comment]
Thanks @heybran. You can proceed with this translation update.

**Comment by heybran** [comment]
Okay, thanks @remibetin

**Comment by heybran** [comment]
Hi @remibetin,

On the Simplified Chinese page: https://www.w3.org/WAI/standards-guidelines/zh-hans, it mentioned that
>Notice: The English original has been substantially updated since this translation. — [修改日志](https://www.w3.org/WAI/standards-guidelines/changelog/)

But in the changelog: https://www.w3.org/WAI/standards-guidelines/changelog/, the lastest changelog documented is **April 2021**, something I missed?

**Comment by remibetin** [comment]
Hi @heybran,

I am currently updating the changelog to help you identify the changes. I will keep you informed very soon (hopefully today).

**Comment by heybran** [comment]
That'd be amazing, thanks @remibetin

**Comment by remibetin** [comment]
@heybran I have published the updated changelog: https://www.w3.org/WAI/standards-guidelines/changelog/

You may also find the GitHub history useful: https://github.com/w3c/wai-std-gl-overview/commits/master/content/index.md

Please also note that I am off until 18 November. Feel free to send your questions in the issues: I will reply soon after my return.

Thanks very much for your patience.

**Comment by remibetin** [comment]
Hi @heybran,

Would you confirm the related Pull Request is ready for review?

Thanks!

**Comment by heybran** [comment]
Hi @remibetin,

Yes, Pull Request is ready for review.

**Comment by remibetin** [comment]
This translation is ready for review! 🎉

Reviewers are welcome to add their comments and collaborate with the translator in the related Pull Request: https://github.com/w3c/wai-website/pull/953

Guidance: https://www.w3.org/WAI/about/translating/guides/review-translation/

**Comment by remibetin** [comment]
@JinMokai Would you be interested in reviewing this translation?

**Comment by remibetin** [comment]
This translation update has been published today 🚀 Thank you @heybran for the translation and @JinMokai for the review!

See https://www.w3.org/WAI/standards-guidelines/zh-hans
