### ISSUE TITLE
[Simplified Chinese] Update UI terms

### ISSUE THREAD

**Issue by remibetin** [w3c/wai-translations#268]
## Context

UI terms have been recently updated. Some Simplified Chinese translations are missing; others need update.

File to edit: https://github.com/w3c/wai-website-data/blob/master/translations.yml

If you are an [existing volunteer,](https://www.w3.org/WAI/about/translating/resources/#intent), please add a comment to volunteer. Then, you can either comment this issue with your translation proposals, or directly open a pull request in [wai-website-data](https://github.com/w3c/wai-website-data) repository.

Add your translation on a new line. For example:

```
- en: 'Example'
  zh-hans: 'Your translation in Simplified Chinese'
```

## New terms to translate

```
# Added 2023-10-03

# The next phrases are combined with page metadata to generate footer (in Tutorials section for example)

- en: 'Editors:'   # gender-neutral, plural. Precedes list of more than one person who edited the resource. If gender-neutral not in your language, use appropriate alternative, such as plural or 'Edition'.

- en: 'Update Editor:'   # gender-neutral, singular. Precedes list of one person who updates the resource. If gender-neutral not in your language, use appropriate alternative, such as plural or 'Update Edition'.

- en: 'Status:' # followed by the last updated date or

- en: 'Updated' #  precedes a date

- en: 'first published' #  precedes a date

# Added 2023-10-18

- en: 'Acknowledgements'

# Added 2024-01-02

- en: 'Video Subtitles' # Precedes list of "subtitles only" translations: https://www.w3.org/WAI/translations/

- en: 'Standards/Guidelines' # Precedes list of translations of standards and guidelines in this language, in https://www.w3.org/WAI/translations/

# Added 2024-03-14

- en: "Long description of image" # Link text underneath an image with long description in another page. Example: https://www.w3.org/WAI/fundamentals/components/

# Added 2024-10-31

- en: 'This page has been reviewed and is current as of' # Used in the page footer

- en: 'Notice:' # Used in “About this translation” section, to notify that the translation needs update.

- en: 'We welcome a <a href="$1">translation update</a>.' # Used in “About this translation” section, when a translation needs update.

- en: 'Translated:'   # Used in the page footer. Precedes the date of the translation.

- en: 'First published'   # Used in the page footer. Precedes the date of the translation.

# Added 2024-11-05

- en: '[include a relevant email Subject]'   # placeholder text in e-mail template
```

## Translations to update

When updated, please move your translation up, before `#  To update`.

```
# Updated 2024-10-31

- en: 'The Web Accessibility Initiative (WAI) thanks translators, and welcomes other <a href="$1">translations</a>.'   # Updated 31-Oct-2024 "WAI thanks translators" -> "The Web Accessibility Inititiative (WAI) thanks translators"
  fr: 'L’Initiative pour l’Accessibilité du Web (WAI) remercie les traducteurs, et accueille volontiers d’autres <a href="$1">traductions</a>.'
  # To update
  zh-hans: 'WAI感谢这些翻译者们，并欢迎其他的<a href="$1">翻译</a>。'

- en: 'The English original has been substantively updated since this translation.'   # Used in “About this Translation” section, when a translation needs update. # Updated 31-Oct-2024 "English version updated since this translation" -> "The English original has been substantively updated since this translation"
  fr: 'La version originale en anglais a été substantiellement mise à jour depuis cette traduction.'
  # To update
  zh-hans: '自该翻译版之后的英文版本更新.'

- en: 'English version updated:'   # Used in page footer and “About this translation" section. Precedes the update date of the English original. # Updated 31-Oct-2024 "English updated:" -> "English version updated:"
  fr: 'Version en anglais actualisée le :'
  # To update
  zh-hans: '英文版本更新：'

- en: 'Translation date:'   # Used in the “About this translation" section. Precedes the date of the translation. # Updated 31-Oct-2024 "Translation updated:" -> "Translation date:"
  fr: 'Date de la traduction :'
  # To update
  zh-hans: '翻译更新'

- en: 'Latest changes'  # Used in page footer and “About this translation" section (when a translation needs update). Links goes to a page listing the changes made to the English original. # Updated 31-Oct-2024 "Changelog" -> "Latest changes"
  fr: 'Derniers changements'
  # To update
  zh-hans: '修改日志'
```

**Comment by codersjj** [comment]
> ## Context
> UI terms have been recently updated. Some Simplified Chinese translations are missing; others need update.
> 
> File to edit: https://github.com/w3c/wai-website-data/blob/master/translations.yml
> 
> If you are an [existing volunteer,](https://www.w3.org/WAI/about/translating/resources/#intent), please add a comment to volunteer. Then, you can either comment this issue with your translation proposals, or directly open a pull request in [wai-website-data](https://github.com/w3c/wai-website-data) repository.
> 
> Add your translation on a new line. For example:
> 
> ```
> - en: 'Example'
>   zh-hans: 'Your translation in Simplified Chinese'
> ```
> 
> ## New terms to translate
> ```
> # Added 2023-10-03
> 
> # The next phrases are combined with page metadata to generate footer (in Tutorials section for example)
> 
> - en: 'Editors:'   # gender-neutral, plural. Precedes list of more than one person who edited the resource. If gender-neutral not in your language, use appropriate alternative, such as plural or 'Edition'.
> 
> - en: 'Update Editor:'   # gender-neutral, singular. Precedes list of one person who updates the resource. If gender-neutral not in your language, use appropriate alternative, such as plural or 'Update Edition'.
> 
> - en: 'Status:' # followed by the last updated date or
> 
> - en: 'Updated' #  precedes a date
> 
> - en: 'first published' #  precedes a date
> 
> # Added 2023-10-18
> 
> - en: 'Acknowledgements'
> 
> # Added 2024-01-02
> 
> - en: 'Video Subtitles' # Precedes list of "subtitles only" translations: https://www.w3.org/WAI/translations/
> 
> - en: 'Standards/Guidelines' # Precedes list of translations of standards and guidelines in this language, in https://www.w3.org/WAI/translations/
> 
> # Added 2024-03-14
> 
> - en: "Long description of image" # Link text underneath an image with long description in another page. Example: https://www.w3.org/WAI/fundamentals/components/
> 
> # Added 2024-10-31
> 
> - en: 'This page has been reviewed and is current as of' # Used in the page footer
> 
> - en: 'Notice:' # Used in “About this translation” section, to notify that the translation needs update.
> 
> - en: 'We welcome a <a href="$1">translation update</a>.' # Used in “About this translation” section, when a translation needs update.
> 
> - en: 'Translated:'   # Used in the page footer. Precedes the date of the translation.
> 
> - en: 'First published'   # Used in the page footer. Precedes the date of the translation.
> 
> # Added 2024-11-05
> 
> - en: '[include a relevant email Subject]'   # placeholder text in e-mail template
> ```
> 
> ## Translations to update
> When updated, please move your translation up, before `# To update`.
> 
> ```
> # Updated 2024-10-31
> 
> - en: 'The Web Accessibility Initiative (WAI) thanks translators, and welcomes other <a href="$1">translations</a>.'   # Updated 31-Oct-2024 "WAI thanks translators" -> "The Web Accessibility Inititiative (WAI) thanks translators"
>   fr: 'L’Initiative pour l’Accessibilité du Web (WAI) remercie les traducteurs, et accueille volontiers d’autres <a href="$1">traductions</a>.'
>   # To update
>   zh-hans: 'WAI感谢这些翻译者们，并欢迎其他的<a href="$1">翻译</a>。'
> 
> - en: 'The English original has been substantively updated since this translation.'   # Used in “About this Translation” section, when a translation needs update. # Updated 31-Oct-2024 "English version updated since this translation" -> "The English original has been substantively updated since this translation"
>   fr: 'La version originale en anglais a été substantiellement mise à jour depuis cette traduction.'
>   # To update
>   zh-hans: '自该翻译版之后的英文版本更新.'
> 
> - en: 'English version updated:'   # Used in page footer and “About this translation" section. Precedes the update date of the English original. # Updated 31-Oct-2024 "English updated:" -> "English version updated:"
>   fr: 'Version en anglais actualisée le :'
>   # To update
>   zh-hans: '英文版本更新：'
> 
> - en: 'Translation date:'   # Used in the “About this translation" section. Precedes the date of the translation. # Updated 31-Oct-2024 "Translation updated:" -> "Translation date:"
>   fr: 'Date de la traduction :'
>   # To update
>   zh-hans: '翻译更新'
> 
> - en: 'Latest changes'  # Used in page footer and “About this translation" section (when a translation needs update). Links goes to a page listing the changes made to the English original. # Updated 31-Oct-2024 "Changelog" -> "Latest changes"
>   fr: 'Derniers changements'
>   # To update
>   zh-hans: '修改日志'
> ```

Hi @remibetin,

I'm eager to contribute. However, I'm not quite sure about one thing: You mentioned, "If you are an existing volunteer, please add a comment to volunteer." I'm not sure I understand what you mean by "add a comment to volunteer." I’ve already sent an email to [group-wai-translations@w3.org](mailto:group-wai-translations@w3.org) and received your response, so I believe I’m already considered an existing volunteer. Could you clarify what exactly I should do to "add a comment to volunteer"?

Thanks!

**Comment by remibetin** [comment]
Thank you @codersjj.

Since our e-mail conversation, you are indeed considered an existing volunteer.

Feel free to proceed with the translation.

**Comment by remibetin** [comment]
The updated terms have been published today 🚀 Thank you @codersjj for the translation and @heybran for the review!
