### ISSUE TITLE
in list of translations, include relevant WAI TR docs

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-translations#28]

**Comment by slhenry** [comment]
Hopefully this will be easy with the new W3C System!

**Comment by slhenry** [comment]
afaik, all still relevant (e.g., not 1.0) are:
* listed here: https://www.w3.org/WAI/standards-guidelines/wcag/translations/
* https://www.w3.org/Translations/ATAG20-zh/

Shawn will coordinate with Dom and new W3C process to confirm if still linking off-site for /TR/ translations.

**Comment by yatil** [comment]
Unsure why this was unassigned from me, I need to add the technical underpinnings to make that happen.

**Comment by slhenry** [comment]
> Unsure why this was unassigned from me, I need to add the technical underpinnings to make that happen.

I guess back then for this:

> Shawn will coordinate with Dom and new W3C process to confirm if still linking off-site for /TR/ translations.

Indeed that's all settled so back to you. :-)

Should use new W3C DB for listings.

**Comment by yatil** [comment]
@yatil to implement that

**Comment by slhenry** [comment]
update: ee & slh decided to use manual list rather than W3C api
