### ISSUE TITLE
Translations disclaimer wording - in Translations Info box

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-translations#3]
At start of issue, straw proposal wording is:
> This volunteer translation might not accurately reflect the intentions of the [English original](@@).

See latest wording proposal in [mock-up](https://w3c.github.io/wai-translation-playground/people-use-web/).

See the [Goals for translation info](https://www.w3.org/wiki/WAI_Translations#Translation_info_.2F_Disclaimer).

fyi, [examples of other wording](https://www.w3.org/wiki/WAI_Translations#Translation_info_.2F_Disclaimer).

In your comment, you might want to quote the wording that you are commenting on, since the wording in the mock-up might change throughout the life of this issue.

**Comment by r12a** [comment]
> Translated:
>     con: can't tweak text later if want
>     pro: non-English speakers can understand it

The pro here is fundamentally important!  That text is not just a bureaucratic requirement, it needs to carry the message to people reading this page (who may not speak English! or who may skip over text in English) that this is only a translation provided on a volunteer basis - ie. it may not reflect the original 100%.

The con is not true. I18n provides that text via inclusion, so we can tweak it if we want to (and we have).  The only problem is to get the new text translated into all languages.

**Comment by yatil** [comment]
Yes, we can change the translated text easily if we want to. I still want a simpler way of saying it.

**Comment by notabene** [comment]
Either simpler or more explaining, this can go both ways. I understand the aim of simplicity but there's the risk mentioned at TPAC that even if we do a review we may end up not being completely fluent in the translation's language, so we may want readers to make sure that we can't really endorse every word in every translation (even if we want to).

I don't know yet how to phrase the warning sentence though.

**Comment by slhenry** [comment]
Given no proposals for different language, closing this issue. Re-open if have suggestions.
