### ISSUE TITLE
Things to do before launching (a preview of) translations

### ISSUE THREAD

**Issue by yatil** [w3c/wai-translations#30]
Not necessarily in this order:

## Implementing Translations

- [x] Develop translation UI from the prototypical implementation and add to the style guide. (6h)
  - [x] Add CSS
	  - [ ] Implementing RTL CSS (maybe later: 6–12h)
  - [x] Add JS
  - [x] Add Templates
  - [x] Add components to existing templates
  - [x] Test styling
- [x] Adapt theme for translations from the prototypical implementation (10h)
	- [x] Copy assets from above
    - [x] Make changes to help improve this page box:
        - [x] <del>Add translate this page button to help improve this page box/translations on the left.</del>
        - [x] Add indicator of language to help improve this page box when writing emails/create GitHub issues (done: w3c/wai-website-theme-beta@a04fb491c80e45ea0765808605ed504306147633)
    - [x] Make sure video player displays language selections in their native language (done: w3c/wai-website-theme-beta@88f7e84453f84ceeb3322a630ab8f95156062554, w3c/wai-video-standards-and-benefits@a1d45804069de820a0ebf4e22d93d6407ec72426 and w3c/wai-video-standards-and-benefits@a962bf68b4ffc1656973a0a8c6f373f107367115)
	- [x] Add and clean up logic in beta theme
	- [x] Add missing functionality
- [x] Test theme and add to resources (12–18h)
	- [x] Use theme in different repositories to test for bugs and missing functionality
	- [x] Identify bugs and missing functionality
	- [x] Fix bugs
	- [x] Add functionality
- [x] Prepare repositories that have translations or will have translations soon (6h)
	- [x] Video Introduction to Web Accessibility and W3C Standards
	- [x] Introduction to Web Accessibility
	- [x] How People with Disabilities use the Web
- [x] Add language overview page, communication on how it should work, testing, bugfixing (20h)
        - [x] First implementation: https://deploy-preview-125--wai-website.netlify.com/translations/
        - [ ] Gather feedback
        - [ ] Implement feedback
- [x] Render and test whole site (4h)
- [ ] <del>Adjust search to only search in the current language (6h)</del>
- [x] Testing for beta/preview (6h)

## Writing Documentation (for translations and beyond) — later

- [ ] Add (a lot) to the editing and publishing documentation at https://www.w3.org/WAI/EO/wiki/Editing_and_Publishing (18h)
- [ ] Figuring out and documenting the translation process (10h)

**Comment by slhenry** [comment]
> Adjust search to only search in the current language (6h)

In 1:1 we said: Probably want option available to get either results only in that language, or all results. SLH to do analysis. Low priority.

**Comment by slhenry** [comment]
Some thoughts to make sure we're in synch. We can discuss in Feb as useful.

> Make sure video player displays language selections in their native language (this might be more complicated in the end, needs investigation.)

Good to have, though maybe not showstopper for soft launch.

> Prepare repositories that have translations or will have translations soon

/me can do some of this

> Figuring out and documenting the translation process

/me planning on doing/helping with most of this documentation

> Adjustments to the translations overview page

I think you're handling the All WAI Translations page and I'm handling the Translating WAI Documents page.

**Comment by slhenry** [comment]
Hi Eric, you probably already know about this [I18N guidance on R-to-L](https://www.w3.org/International/techniques/authoring-html?open=direction#direction).

**Comment by yatil** [comment]
Closing this catch-all issue.
