### ISSUE TITLE
[medium] Make phrases not break across lines

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-translations#33]
Consider for:
* "All Translations [icon]"
* "This page in: English"
* "Hide options [-]"

Note: implications for existing translations in yml file?

**Comment by yatil** [comment]
I don’t understand. You want non-breaking spaces there? That might lead to horizontal scrolling for screen magnification/zoom users.

**Comment by yatil** [comment]
I changed this although I think in the confined space of that header area we should allow line breaks. Change won’t be visible immediately.

**Comment by slhenry** [comment]
Thanks.

Those phrases not breaking across lines is much better for general usability, visual design, and cognitive accessibility. I think potential for problems is low. We can do more testing and get more input if useful.
