### ISSUE TITLE
[All Translations] consider adding English resource name in (parenthesis)

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-translations#40]
question:
* limited user need? mostly staff?

for:
* helpful for English speakers to know

against:
* more clutter

**Comment by yatil** [comment]
@yatil To put table with English title on it

**Comment by yatil** [comment]
Will be fixed with: https://github.com/w3c/wai-website/pull/167

**Comment by slhenry** [comment]
woo-hoo!
