### ISSUE TITLE
Page titles in language link to English version

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-translations#42]
- [x] EE: for links within the content, the system adds "(in English)"[in language] next to page titles (per [Language of links/resource titles within the content](https://www.w3.org/wiki/WAI_Translations#Language_of_links.2Fresource_titles_within_the_content) & [Language of links to other pages](https://github.com/w3c/wai-translations/issues/8))
- [ ] SLH or EE: fix added links in Video Intro pages (in English version and all the updated translations)
- [x] <del>SLH or EE: delete redundant (in English) in Russian -- and French ***after*** we get the update</del>

**Comment by yatil** [comment]
See https://github.com/w3c/wai-video-standards-and-benefits/pull/38 for changes that should fix this issue.

**Comment by slhenry** [comment]
- [ ] Still need to check Russian after all pull requests are merged.

For everything else per https://github.com/w3c/wai-video-standards-and-benefits/pull/38
* OK for now.
* Need to fix some text->fallback **later**.

**Comment by slhenry** [comment]
Closing this broad issue. Leaving the for later fixes in w3c/wai-video-standards-and-benefits#38
