### ISSUE TITLE
[All Translations page] Add translator and contributor names to listing

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-translations#47]
_(related issue: [consider adding English resource name in (parenthesis) ](https://github.com/w3c/wai-translations/issues/40))_

Format for both:

* [document title in language] ([title in English]) &mdash; ["Translator" in language]: [name]. ["Contributor" in language]: [name].

e.g.
> Video-Einführung in Web-Accessibility und W3C-Standards (Video Introduction to Web Accessibility and W3C Standards) &mdash; Übersetzung: Sandra Kallmeyer. Mitwirkende(r): Stefanie Hegele.

**For short term can just add translator for now:**
* [document title in language] &mdash; Translator: [name]

e.g.
> Video-Einführung in Web-Accessibility und W3C-Standards  &mdash; Translator: Sandra Kallmeyer

**Comment by yatil** [comment]
Strongly –1 to mixing English into the titles, the language changes we already have on the page seem to overwhelm people.

**Comment by yatil** [comment]
The only open aspect, English page names, is in #40. So closing this issue.

**Comment by slhenry** [comment]
Actually, current short-term implementation is:
* [document title in language] — Translator: [name]

First suggestion above -- without title in English -- is:
* [document title in language] — ["Translator" in language]: [name]. ["Contributor" in language]: [name].

e.g.
> Video-Einführung in Web-Accessibility und W3C-Standards &mdash; Übersetzung: Sandra Kallmeyer. Mitwirkende(r): Stefanie Hegele.

I think having translator and contributor in the language is good to address your comment of changing the language back and forth. ;-) Although I don't feel strongly and could be convinced otherwise pretty easily. :)

**Comment by yatil** [comment]
The bug is now fixed and Translator/Contributor is shown in the language.

**Comment by yatil** [comment]
… as it was previously intended ;-)
