### ISSUE TITLE
[on-going] UI yml updates - list for translators

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-translations#48]
Let's batch minor edits and additions, and ask for updated translations when we have important ones or several minor ones.

* ["WAI thanks these translators" -> "WAI thanks translators"](https://github.com/w3c/wai-website-data/commit/f642fd1a98cd884958bc2fca703fdc412d264833#diff-9d31a970248a8964164d48b618b6060b)
* [ADDED 2019-June-28 main navigation links](https://github.com/w3c/wai-website-data/commit/5a953e3aea618527986422b3dc7de0e2a9508eeb#diff-9d31a970248a8964164d48b618b6060b)

**Comment by yatil** [comment]
_/me considers moving this issue to w3c/wai-website-data so that translators can find the info there._

**Comment by yatil** [comment]
FYI: I also added the new verbiage to the theme. If the English from the theme is not a 100% match with the lookup text from the yaml file, the lookup fails and English text is displayed on other language pages.

**Comment by slhenry** [comment]
Makes sense. Good to add to forthcoming documentation so I don't forget. :)

**Comment by slhenry** [comment]
> /me considers moving this issue to w3c/wai-website-data so that translators can find the info there.

I still can't figure out where things are. /me just searched round & round for a GitHub issue that I knew existed but didn't know in which repo.

I've meant to put most issues related to translations in general in this repo. That's best for me for finding things and getting To Do list. But I know that doesn't match with your [GitHub]worldview. We'll figure it out. :-)
