### ISSUE TITLE
All Translations Page - image in empty left space

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-translations#49]
Hey @yatil 

The left side of https://www.w3.org/WAI/translations/ looks empty and odd. I **love** the content of that page (and keep pointing others to it!), yet that one thing keeps niggling at me.

What do you think of putting [this icon](http://www.languageicon.org/) in that left nav area?

Maybe as big as that nav area usually is wide? Probably in one of the site blues.

**Comment by yatil** [comment]
We can do that but it basically means creating a whole new template for it. I personally think we should address that more systematically, maybe with the menu redesigns that we are planning anyway.

(For reference, those are the following issues: https://github.com/w3c/wai-website/issues/154, https://github.com/w3c/wai-website/issues/138, https://github.com/w3c/wai-website/issues/126)

**Comment by yatil** [comment]
@slhenry I have published an initial version here: https://www.w3.org/WAI/translations/

**Important:** If the big icon is black instead of blue, clear your cache. I had a bug in the initial icon, thus not being able to change the color using CSS.

Let me know if you want me to make changes.

**Comment by slhenry** [comment]
It's **_beautiful_**! I love it!!!
