### ISSUE TITLE
[French] Involving Users in Web Projects for Better, Easier Accessibility

### ISSUE THREAD

**Issue by remibetin** [w3c/wai-translations#59]
Original page: https://www.w3.org/WAI/planning/involving-users/

Main contributor: miss-poullon

PR opened: 
- https://github.com/w3c/wai-website/pull/488

**Comment by remibetin** [comment]
This translation has been published today 🚀 Thank you @miss-poullon!

See https://www.w3.org/WAI/planning/involving-users/fr

**Comment by miss-poullon** [comment]
Thank you so much for your great support @remibetin!
