### ISSUE TITLE
how to show translations on a page (list always visible, select expand/collapse, drop-down, etc.)

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-translations#6]
**NOTE: The proposal changed since this first comment. The latest proposal is lower in this issue.**

Proposed: select expand/collapse to get the list<s>, as in [mock-up](https://w3c.github.io/wai-translation-playground/people-use-web/)</s>

Before commenting on other options, please read [details on **Always visible vs. Select** in wiki](https://www.w3.org/wiki/WAI_Translations#Always_visible_vs._Select).

**Comment by slhenry** [comment]
_moved from https://github.com/w3c/wai-translations/issues/7_
**@r12a said:**


In my opinion, using a pulldown to select languages should be avoided whenever possible, and is only really needed when you have quite a large number of alternatives to choose from.  (See https://www.w3.org/International/questions/qa-navigation-select#proscons.)  If you use a pulldown control, you really can't use text for the label, since it will be difficult for someone to find if they don't speak the language that the label is written in.  However it is also difficult to find a graphic alternative that is readily recognisable.

In the mockup, the label for the pulldown is in English even though the page is in French. Is that intentional? I think, if you are going to have text, it should be in French.

![screen shot 2018-10-18 at 08 17 07](https://user-images.githubusercontent.com/4839211/47139403-a8563100-d2b3-11e8-92aa-839eac42cc20.png)

I strongly recommend using a list of links, rather than a pulldown control. The link text of each should be the name of the language of the target page, written in that language.

**Comment by slhenry** [comment]
_moved from https://github.com/w3c/wai-translations/issues/7_
**@yatil said:**

@r12a 

> I strongly recommend using a list of links, rather than a pulldown control. 

We are not using a pulldown, it is more an expand/collapse :-) The reason why the button is English on the French version is that if someone gets to the translated page by accident, they would probably find it easier to find the option to change the language in English than in French.

> If you use a pulldown control, you really can't use text for the label, since it will be difficult for someone to find if they don't speak the language that the label is written in. However it is also difficult to find a graphic alternative that is readily recognisable.

That’s why we use an icon with the text “show languages”.

> The link text of each should be the name of the language of the target page, written in that language.

That’s what we do.

**Comment by slhenry** [comment]
@yatil &mdash; pulldown, drop-down list, expand/collapse all have the same con that users don't see their language until they interact with the control -- and they are less likely to recognize an icon and the wording "Select Language" or "Translations" or whatever we go with than they are their language in their language.

@r12a &mdash; Yes, those cons are listed under [**List vs. Select and Select options** in wiki](https://github.com/w3c/wai-translations/wiki/WAI-Translations-Overall-Approach,-Issues,-etc#list-vs-select).

Personally I'm "on the fence" on this one. I totally agree that having the languages visible up front is better usability. I'm just not sure in our situation if it is worth the space...

**Comment by slhenry** [comment]
> The reason why the button is English on the French version is that if someone gets to the translated page by accident, they would probably find it easier to find the option to change the language in English than in French.

+1

**Comment by yatil** [comment]
@slhenry 

> @yatil — pulldown, drop-down list, expand/collapse all have the same con that users don't see their language until they interact with the control -- and they are less likely to recognize an icon and the wording "Select Language" or "Translations" or whatever we go with (Labelling options) than they are their language in their language.

Point taken. (/me thinks the right side gutter that we had in some early mockups would be useful for this, but as we don’t have one, I don’t think there is a good spot to list all the languages w/o a drop down… :-/)

**Comment by slhenry** [comment]
We're going to try options for listing all languages without select!

**Comment by slhenry** [comment]
Proposal: List of translations always visible in left column after section navigation, as in **[mock-up](https://w3c.github.io/wai-translation-playground/people-use-web/#languagehead)**.
