### ISSUE TITLE
[French] The Business Case for Digital Accessibility

### ISSUE THREAD

**Issue by remibetin** [w3c/wai-translations#65]
Minor changes (typos, orthotypographic changes, machine-learning translation)

Current translation page: https://www.w3.org/WAI/business-case/fr

PRs opened:
- https://github.com/w3c/wai-bcase/pull/121
- https://github.com/w3c/wai-bcase/pull/122

**Comment by shawna-slh** [comment]
merged.

**Comment by shawna-slh** [comment]
Published. Please QA.

**Comment by remibetin** [comment]
@shawna-slh QA done: all good ✅
