### ISSUE TITLE
[French] WCAG-EM Report Tool

### ISSUE THREAD

**Issue by remibetin** [w3c/wai-translations#76]
Original page: [WCAG-EM Report Tool: Website Accessibility Evaluation Report Generator ](https://www.w3.org/WAI/eval/report-tool/)

2 volunteer translations:
- https://github.com/w3c/wai-wcag-em-report-tool/pull/91 by ericporlier (oct. 2021)
- https://github.com/w3c/wai-wcag-em-report-tool/pull/127 by mthiebaut (june 2023)

Review in https://github.com/w3c/wai-wcag-em-report-tool/pull/127

**Comment by KodGit** [comment]
Hi Remi,

This new French translation of the report tool is especially based on the WCAG 2.1 FR translation (published by W3C in july 22).
https://github.com/w3c/wai-wcag-em-report-tool/pull/127 by mthiebaut (june 2023)

The oldest one seemed to be based on a non official FR translation of the WCAG 2.0
https://github.com/w3c/wai-wcag-em-report-tool/pull/91

If you have any question with the pull request #127, i would be pleased to answer about that work (by States of Geneva https://www.ge.ch and Digital Public Services Switzerland https://www.digital-public-services-switzerland.ch/)

Best regards,
Alex (Project Manager States of Geneva)

**Comment by remibetin** [comment]
Hi @KodGit 

Thank you for your reply and volunteering to translate WCAG-EM Report Tool.

Considering the 2 opened Pull Requests, I suggest the following next steps:

- Could you please confirm to me that your team has read and understood the information on Translating WAI Documents at[ https://www.w3.org/WAI/about/translating/](https://www.w3.org/WAI/about/translating/)?

- Would you be willing to work together with @ericporlier, to review each other’s contribution and come out with a common version? You can do that directly in the GitHub Pull Requests, or by e-mail (in that case, please CC group-wai-translations@w3.org).

- In the meantime, in accordance with the [translation policy](https://www.w3.org/copyright/intellectual-rights/#translations), can you please include the following information in a prominent location on the version hosted at[ https://wcag-outils.ge.ch/](https://wcag-outils.ge.ch/):
  - a reference to the original document.
  - that the official version of the tool is the English version found at the W3C site.
  - that the translated document may contain errors from the translation.

Regards,

Remi.
cc @mthiebaut @ivandalbosco

**Comment by KodGit** [comment]
Hi @remibetin 

Thank you for your message.

- I confirm that we have red and understood the information on translating WAI Documents
- Unfortunately, the work done by @ericporlier is outdated (Oct 2021) as it was based on the french translation of the WCAG 2.0 (jun 2009). Our work was based on the last french translation of the WCAG 2.1 (Jul 2022) including WCAG 2.0 and WCAG 2.1 add-on. Our team was french native speakers, accessibility specialist and digital experts.  
- The experimental lab hosted att https://wcag-outils.ge.ch was made to share that translation with our french speacking accessibility network (access42.fr, access-for-all.ch, ...). I propose to had a restricted access to this lab during the validation of the french translation. We are already using this frecnh lab of the report tool to evaluate our public digital services. We wish that we could soon use an official version of it hosted by the W3C.

During the next month, we will work on the french translation of the WCAG 2.2 with Access42.fr and we will probably work to had a nex pull request for the report-tool bext year.

Best regards,

Alex

cc @mthiebaut @ivandalbosco

**Comment by KodGit** [comment]
Dear @remibetin

A disclaimer is now present on all the main pages of the french translation of the WCAG-EM Report Tool hosted at https://wcag-outils.ge.ch/

We are already using it to evaluate digital public services accessibility for the State of Geneva and we'd like to promote it's use widely over the swiss french language organisations. The Digital Public Services Switzerland (DPSS) https://www.digital-public-services-switzerland.ch/ is supporting this work that match with the eCH-0059 swiss accessibility standards  https://www.ech.ch/fr/ech/ech-0059/3.0.

Could you tell me what is the next step to review and validate our contribution ?

Best regards 

Alex

cc @mthiebaut @ivandalbosco

**Comment by remibetin** [comment]
Hi @KodGit 

I'm sorry for the delay, thank you for your patience.

> A disclaimer is now present on all the main pages of the french translation of the WCAG-EM Report Tool hosted at https://wcag-outils.ge.ch/

Thank you for adding the disclaimer.

> Could you tell me what is the next step to review and validate our contribution ?

I will make some time to review your contribution next week. Review discussions will take place in your PR.

cc @mthiebaut @ivandalbosco

**Comment by KodGit** [comment]
Hi @remibetin

Thanks very much for the update.
I look forward to hearing from you.
 
cc @mthiebaut @ivandalbosco

**Comment by remibetin** [comment]
@KodGit @mthiebaut @ivandalbosco @ericporlier Your translation of the WCAG-EM Report Tool into French has finally been published! Visit https://www.w3.org/WAI/eval/report-tool/ and choose "Français" at the top of the page.

Thank you very much! We acknowledge your contributions in the [Acknowledgements page](https://www.w3.org/WAI/eval/report-tool/acknowledgements) of the tool, and in the [All WAI Translations](https://www.w3.org/WAI/translations/) page.

Please note that I have added a banner to the translation stating the translation may contain English wording. You have translated everything you could, but WCAG 2.2. success criteria have been added and are not translated yet, and some parts of the UI are not translatable yet.
