### ISSUE TITLE
[French] Teach and Advocate Overview

### ISSUE THREAD

**Issue by remibetin** [w3c/wai-translations#79]
Minor changes.

Original page: [Teach and Advocate Overview](https://www.w3.org/WAI/teach-advocate/)

Contributor: @3l3gant-cod3s

PR opened: https://github.com/w3c/wai-teach-advocate-overview/pull/21

**Comment by remibetin** [comment]
Live 🎉 : https://www.w3.org/WAI/teach-advocate/fr

Thank you @3l3gant-cod3s!

**Comment by 3l3gant-cod3s** [comment]
you're welcome!
