### ISSUE TITLE
Language of links to other pages - shouldn't indicate the language of the destination

### ISSUE THREAD

**Issue by r12a** [w3c/wai-translations#8]
? Leave the title in English and include in the link "(in English)" in that language, e.g.,
Stories of Web Users (en anglais)

This is a tricky one. Basically, it makes sense to warn readers if the link goes to a page that is not in the same language.  However, adding '(en anglais)' could very quickly become incorrect when someone is providing French translations and translates that page.  If a translation becomes available, you don't want to leave it there as it is likely to discourage people from following the link (that's why you put the warning there in the first place, right?), but searching for all links to the newly translated page in order to remove the 'en anglais' warning would quickly become extremely painful to maintain. 

The only good solution i can think of is to automatically find out whether there is a translation of that resource in the same language, as the page is displayed, and modify the link text while the page is rendered.   For the i18n pages, we could actually do something like that for our articles, i believe, because we are able to query whether a given article is translated or not into a given language, however we don't currently do so.

**Comment by yatil** [comment]
We will be able to test if a translation exists and automatically re-write the link when the page is generated. (I guess that is a todo for me :-D)

**Comment by yatil** [comment]
> Will that require extra code/markup around each link?

Unfortunately, yes. (Links would look like `{% include_cached link.html text="Linktext" path="/to/page/" class="(optional)" format="(optional)" %}` or so. I don’t think it’ll be too bad in the end.)

**Comment by notabene** [comment]
+1 for automation

**Comment by yatil** [comment]
> What about links to non-WAI pages? Translate the title but don't include a language?

If the link is in a sentence, it should be translated. If it is a stand-alone link, I lean towards keeping the English title w/`lang=en`&`hreflang=en`.

**Comment by slhenry** [comment]
For the overall issue of links in English or translated (when the resulting page is in English or we don't know if it is translated), I'd like to understand different user experience considerations. For example:
* When reading sentences in my language, it is smoother if the link is in that language. If it's in English, it's jarring and takes more effort to process.
* If I'm reading through navigation (list of links), it's easiest for me if they are in the language of the resulting page -- that makes it easiest for me to know if they're in my language or in English. (If the page titles are translated, then I read the title in my language, then process "(in English)" and see I can't understand it anyway.)
* When I come to a page that I think is is my language, yet much of what I first see (header, navigation) is in English, I think the page I'm on is not in my language.
* ...

I hope next week we can get some shared understanding around these experiences and perspectives. Of course, different people will have different preferences -- and there are some technical, back-end, and management considerations -- so we probably won't have a solutions that works equally well for all people. I do think we'll be able to come up with an informed decision anyway. :-)

**Comment by r12a** [comment]
> Given the types of pages we link to, it would be extremely rare that we link to a page in English that later becomes available in the translated language.

Without reopening the issue, i'll just note here that it's quite probable that any i18n articles you link to will later become available in the translated language. ;-)

**Comment by slhenry** [comment]
Got it, @r12a.

I think the only i18n articles that WAI pages link to will be in our Instructions to Translators, e.g., https://www.w3.org/International/2004/06/translation-checklist (and it looks like that one is not translated at all -- which makes sense since most people using that content are translators who know English).
