### ISSUE TITLE
[Indonesian] Mobile Accessibility at W3C

### ISSUE THREAD

**Issue by remibetin** [w3c/wai-translations#84]
Original page: https://www.w3.org/WAI/standards-guidelines/mobile/

Pull Request Ready for Review: 
- https://github.com/w3c/wai-mobile/pull/38

Translator: @frirasyidi

**Comment by frirasyidi** [comment]
@remibetin the translation is ready for review

**Comment by remibetin** [comment]
This translation is ready for review! 🎉

Reviewers are welcome to add their comments and collaborate with the translator in the related Pull Request: https://github.com/w3c/wai-mobile/pull/38
