### ISSUE TITLE
Edits to English version - process implications

### ISSUE THREAD

**Issue by r12a** [w3c/wai-translations#9]
If the translation is not up to date, there are a number of questions about what should be done with this page.

For i18n articles, 

- if the changes to the English version are very small nits and don't involve text that needs translation we simply propagate the changes through all translations.
- if the changes are small editorial tweaks, but involve natural language text, we typically add the new English text to the translations while waiting for translators to provide an update.  If no update if forthcoming, the English text may remain there.
- if there are substantive changes we normally add a strong warning at the top of the page and give translators  a month to provide an updated translation. If that is not forthcoming, we remove the links to the out of date translation.

**Comment by yatil** [comment]
-1 to remove translations, even if they are outdated unless we correct mistakenly false information. Having slightly out of date translations is better than not providing them.

**Comment by notabene** [comment]
I like the way @r12a summed it in at f2f: “If I don't want to see this content in print.” It's a good fathom that we must keep at the back of our heads. Slightly unaccurate is OK, wholly mistaken is not (like if some time in the future we turn a notion on its head and all of a sudden a point that was translated looks like we could be ashamed to endorse it).
So +1 to keep it on track somewhere, even if for the moment it's a theoretical question.

**Comment by yatil** [comment]
FWIW that is why we need to keep translators in the loop for major changes and tag them when we plan or raise issues or merge changes. They might be at least able to add a “this section is outdated” note in the short run.

**Comment by slhenry** [comment]
https://www.w3.org/WAI/about/translating/#updating-resources
